geoblacklight/geoblacklight

- template.rb
Need to add rails-assets gem source so bundle install can run without errors. Closes #254
> add rails-assets as gem source

- app/assets/stylesheets/geoblacklight/modules/home.scss
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_home_text.html.erb
- app/views/catalog/_search_form_no_navbar.html.erb
After Blacklight 5.8.2 update search bar on home page was displaying incorrectly, this fixes it.
> fixes search bar display on homepage

- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_abstract_metadata.html.erb
- app/views/catalog/_upper_metadata.html.erb
- lib/generators/geoblacklight/templates/catalog_controller.rb
- spec/features/show_page_metadata_spec.rb
Partially addresses #241 
Enables show field configuration (a Blacklight feature) which was previously disabled. Also adds a linked search to "Held by" institution.
> enables show field configuration in CatalogController

- geoblacklight.gemspec
Blacklight Range Limit had a bug that was causing JavaScript errors when an item had a zero in its year field
> update BL range limit to fix zero bug

- app/assets/stylesheets/geoblacklight/_geoblacklight.scss
- app/assets/stylesheets/geoblacklight/modules/icon-customization.scss
- app/assets/stylesheets/geoblacklight/modules/toolbar.scss
- app/views/catalog/_document_action.html.erb
After document actions framework implemented, icons went away. Now they are back!
> adds back in icons to toolbar

- lib/geoblacklight/controller_override.rb
- spec/features/split_view.html.erb_spec.rb
This fixes the rest of the problem. They q param to solr wasn't really what we wanted and was causing results to not show up which intersected.
> use boost query rather than q

- lib/generators/geoblacklight/install_generator.rb
- lib/geoblacklight/routes.rb
Closes #287 
So new routes can added or modified in GeoBlacklight without causing adopters too much pain
This might be controversial... what do others think?
> remove route adds from generator

- app/controllers/download_controller.rb
- lib/geoblacklight/download.rb
- lib/geoblacklight/download/geojson_download.rb
- lib/geoblacklight/download/geotiff_download.rb
- lib/geoblacklight/download/hgl_download.rb
- lib/geoblacklight/download/kmz_download.rb
- lib/geoblacklight/download/shapefile_download.rb
- spec/controllers/download_controller_spec.rb
- spec/features/download_layer_spec.rb
- spec/lib/geoblacklight/download/geojson_download_spec.rb
- spec/lib/geoblacklight/download/geotiff_download_spec.rb
- spec/lib/geoblacklight/download/hgl_download_spec.rb
- spec/lib/geoblacklight/download/kmz_download_spec.rb
- spec/lib/geoblacklight/download/shapefile_download_spec.rb
- spec/lib/geoblacklight/download_spec.rb
Does a few things here:
- moves `Download` classes underneath the `Geoblacklight` module. 656c316
- Allows subclassed downloads to take an options parameter which gets merged in. This allows for a `timeout` parameter that can be configured individually on instantiation independent of an apps configuration
> Configure download

- app/controllers/download_controller.rb
- config/locales/geoblacklight.en.yml
- lib/geoblacklight/download.rb
- lib/geoblacklight/exceptions.rb
- spec/controllers/download_controller_spec.rb
- spec/features/download_layer_spec.rb
- spec/lib/geoblacklight/download_spec.rb
Does several things:
- rather than returning `nil` errored downloads raise `Geoblacklight::Exceptions::ExternalDownloadFailed`
- in `DownloadController` rather than checking for `nil` rescue from `Geoblacklight::Exceptions:ExternalDownloadFailed`
- adds a test for an errored download message
- provides a url to the errored download try to the user in a flash message
- updates documentation for `Download` class
> updates Downloads to handle errors better

- lib/generators/geoblacklight/templates/catalog_controller.rb
- spec/features/bookmarks_spec.rb
Make sure that config[:document] is available ... this was causing an error on bookmarks page.
> quick fix to error when using bookmarks and document actions framework

- lib/geoblacklight/search_builder.rb
- spec/lib/geoblacklight/search_builder_spec.rb
This pull request fixes a bug where `: add_spatial_params` was being added on every request to `processor_chain` resulting with an extremely long Solr query.
Thanks to @cbeer for helping diagnose and propose a fix.
> check to see if method is already in search builder

- app/assets/javascripts/geoblacklight/viewers/map.js
- app/assets/javascripts/geoblacklight/viewers/wms.js
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_document_split.html.erb
- app/views/catalog/_home_text.html.erb
- app/views/catalog/_show_default_viewer_container.html.erb
- lib/generators/geoblacklight/templates/catalog_controller.rb
- lib/geoblacklight/version.rb
- spec/features/configurable_basemap_spec.rb
- spec/helpers/geoblacklight_helpers_spec.rb
Adds in the ability to configure the basemap. This functionality can be extended in a user's own app:
in a GeoBlacklight apps `app/assets/javascripts/geoblacklight.js`
```javascript
GeoBlacklight.Viewer.Map = GeoBlacklight.Viewer.Map.extend({
selectBasemap: function() {
var _this = this;
return //anything!;
}
});
```
or add more basemaps:
```javascript
GeoBlacklight.Viewer.Map = GeoBlacklight.Viewer.Map.extend({
basemap: {
stamenWatercolor: L.tileLayer(
'http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.{ext}', {
attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
subdomains: 'abcd',
minZoom: 1,
maxZoom: 16, …
```
> add configurable basemap

- lib/geoblacklight.rb
- lib/geoblacklight/solr_document.rb
- lib/geoblacklight/solr_document/finder.rb
- lib/tasks/geoblacklight.rake
- spec/lib/geoblacklight/solr_document/finder_spec.rb
This pull request adds class methods for finding Solr documents to the `Geoblacklight::SolrDocument` class. Also enables the ability to precache downloads using a rake task.
Rake task call would look something like: 
```sh
$ rake 'geoblacklight:downloads:precache[tufts-cambridgegrid100-04, shapefile, 50]'
```
> Solr doc fetch... and precache downloads

- lib/geoblacklight.rb
- lib/geoblacklight/bounding_box.rb
- lib/geoblacklight/exceptions.rb
- lib/geoblacklight/search_builder.rb
- spec/features/search_bar_spec.rb
- spec/lib/geoblacklight/bounding_box_spec.rb
- spec/lib/geoblacklight/search_builder_spec.rb
Closes #333 & closes #332 
Preliminary testing with Solr 4.10.4 and Solr 5.1 and spatial search seems to be functional. Holding off on  using Solr 5.x in tests until Blacklight does so. https://github.com/projectblacklight/blacklight/pull/1100
> switch from querying solr using rectangle to envelope syntax

- Gemfile
With the latest bootstrap-sass release, we can now remove this from the gem's Gemfile.
> remove bootstrap-sass gem version locks

- Gemfile
- Rakefile
- spec/javascripts/geoblacklight_spec.js
- spec/javascripts/spec_helper.js
- spec/teaspoon_env.rb
- spec/test_app_templates/lib/generators/test_app_generator.rb
- enables JavaScript specs (see spec/javascripts/geoblacklight_spec.js)
- should allow us to start better testing the JavaScript as more complexity is added.
- uses Jasmine
*Note:* engine_cart:clean && engine_cart:generate will need to be ran
> Add JavaScript testing framework Teaspoon

- app/assets/stylesheets/geoblacklight/modules/icon-customization.scss
- app/assets/stylesheets/geoblacklight/modules/toolbar.scss
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_exports.html.erb
- lib/generators/geoblacklight/templates/catalog_controller.rb
- lib/generators/geoblacklight/templates/settings.yml
- lib/geoblacklight.rb
- lib/geoblacklight/download.rb
- lib/geoblacklight/solr_document.rb
- lib/geoblacklight/solr_document/carto_db.rb
- spec/features/exports_spec.rb
- spec/features/split_view.html.erb_spec.rb
- spec/fixtures/solr_documents/public_direct_download.json
- spec/lib/geoblacklight/download_spec.rb
- spec/lib/geoblacklight/solr_document/carto_db_spec.rb
Adds an "Open in CartoDB" link to toolbar for public docs with a wfs web service
This also opens up the possibility of adding in a "Open in ArcGIS.com" link as well, but there are still some information barriers before adding that feature.
> add exports to toolbar, implementing export to CartoDB

- geoblacklight.gemspec
- Later versions of `rails_config` changes the name to `config` causing issues
Closes #345
> Pin to rails_config v0.4.x

- app/assets/javascripts/geoblacklight/basemaps.js
- app/assets/javascripts/geoblacklight/viewers/wms.js
'detectRetina' documented [here](http://leafletjs.com/reference.html#tilelayer-detectretina):
> If true and user is on a retina display, it will request four tiles of half the specified size and a bigger zoom level in place of one to utilize the high resolution.
> Add detectRetina option for Leaflet basemaps and WMS layers

- app/helpers/geoblacklight_helper.rb
- lib/geoblacklight.rb
- lib/geoblacklight/solr_document.rb
- lib/geoblacklight/solr_document/inspection.rb
- spec/features/metadata_panel_spec.rb
- spec/lib/geoblacklight/solr_document/inspection_spec.rb
Add configurable inspection logic to solr document. Pulled from ESRI service support PR #335.
> add inspection logic to solr document

- app/assets/javascripts/geoblacklight/modules/layer_opacity.js
- app/assets/javascripts/geoblacklight/viewers/map.js
- app/assets/javascripts/geoblacklight/viewers/wms.js
- app/assets/stylesheets/geoblacklight/modules/item.scss
- app/views/catalog/_show_default_viewer_container.html.erb
- spec/features/layer_opacity_spec.rb
Pulls layer opacity control up into map.js module from wms viewer. Pulled from ESRI service support PR #335.
> refactor layer opacity control

- .gitignore
- Gemfile
- Rakefile
- geoblacklight.gemspec
- spec/test_app_templates/lib/generators/test_app_generator.rb
Note to developers: this changes the location of the test app. Test app location now at `.internal_test_app`
> Update to Engine Cart v0.8 in preparation of Blacklight 6

- CONTRIBUTING.md
- README.md
This allows us to take advantage of this feature from GitHub: https://github.com/blog/1184-contributing-guidelines
> move contributing section to CONTRIBUTING.md

- app/helpers/geoblacklight_helper.rb
- app/models/concerns/geoblacklight/solr_document.rb
- app/views/catalog/_downloads.html.erb
- config/locales/geoblacklight.en.yml
- lib/generators/geoblacklight/templates/settings.yml
- spec/features/download_layer_spec.rb
- spec/helpers/geoblacklight_helpers_spec.rb
- spec/models/concerns/geoblacklight/solr_document_spec.rb
I took another quick stab at this. Not sure if it's the most elegant way of going about it... but it does bypass the download controller, so the "Download JPG" button will directly open a `/full/full/0/default.jpg` image in a new window.
Any thoughts? (Also, just to clarify, should I not have pushed this to a branch on the `geoblacklight/geoblacklight` repo? If so, I'll do this on a fork next time.)
> Adds JPG download button when IIIF reference present

- app/helpers/geoblacklight_helper.rb
- spec/helpers/geoblacklight_helpers_spec.rb
Removes any whitespace from `application_name` before sending it as the `provider` param.
Referenced in https://github.com/geoblacklight/geoblacklight/issues/386
Issue on the CartoDB side already documented here https://github.com/CartoDB/cartodb/issues/6092
> Fixes CartoDB OneClick multi-value application name bug

- lib/geoblacklight/download.rb
- spec/lib/geoblacklight/download_spec.rb
To get around an error in which GeoServer returns a download with a Content-Type that is correct, but more detailed than what was requested. Like when `application/json` is requested but the download from GeoServer is `application/json; chartype=UTF-8`
> uses simplified MIME type of download for comparison

- app/assets/javascripts/geoblacklight/viewers/map.js
- app/assets/javascripts/geoblacklight/viewers/viewer.js
- app/assets/javascripts/geoblacklight/viewers/wms.js
- app/views/catalog/_document_split.html.erb
- app/views/catalog/_home_text.html.erb
- lib/generators/geoblacklight/templates/settings.yml
Make leaflet retina detection configurable in `settings.yml`. This directly impacts all base maps as well as the `wms` viewer. Closes #415.
> Make detect retina configurable

- lib/tasks/configure_solr.rake
- schema/geoblacklight-schema.md
- schema/solr/conf/schema.xml
- schema/solr/conf/solrconfig.xml
This PR fixes #425. It creates a `schema/` folder in the repo and puts the Solr configuration files and the documentation on the schema there. 
The rake task `geoblacklight:configure_solr` now takes an optional argument for the Solr version.
> migrate v0.3.0 GeoBlacklight Schema into local repo

- lib/generators/geoblacklight/install_generator.rb
Routes to item show pages were going to `/solr_documents/:id` instead of  `catalog/:id`. This fixes it.
> Route to catalog instead of solr_documents

- spec/features/linkified_attribute_table_spec.rb
The fixture used in the linkified_attribute_table_spec changed it's id. This PR corrects it.
> Correct fixture name in linkfy test

- app/assets/stylesheets/geoblacklight/_geoblacklight.scss
- app/assets/stylesheets/geoblacklight/modules/twitter-typeahead.scss
Fixes issue https://github.com/geoblacklight/geoblacklight/issues/437 by including twitter-typehead scss from Blacklight core as a geoblacklight module.
> Fix for typeahead / search span issue

- lib/tasks/geoblacklight.rake
- schema/geoblacklight-schema.json
- schema/geoblacklight-schema.md
- schema/solr/conf/schema.xml
- spec/fixtures/solr_documents/actual-papermap1.json
- spec/fixtures/solr_documents/actual-point1.json
- spec/fixtures/solr_documents/actual-polygon1.json
- spec/fixtures/solr_documents/actual-raster1.json
- spec/fixtures/solr_documents/esri-dynamic-layer-all-layers.json
- spec/fixtures/solr_documents/esri-dynamic-layer-single-layer.json
- spec/fixtures/solr_documents/esri-feature-layer.json
- spec/fixtures/solr_documents/esri-image-map-layer.json
- spec/fixtures/solr_documents/esri-tiled_map_layer.json
- spec/fixtures/solr_documents/esri-wms-layer.json
- spec/fixtures/solr_documents/harvard_raster.json
- spec/fixtures/solr_documents/public_direct_download.json
- spec/fixtures/solr_documents/public_iiif_princeton.json
- spec/fixtures/solr_documents/public_polygon_mit.json
- spec/fixtures/solr_documents/restricted-line.json
This PR is connected to #393. It does the following:
- switches to `layer_slug_s` as the primary key in Solr index
- adds support for the `_im` suffix in the Solr index
- deprecates the fields in #393 and drops them from the fixtures
- adds `geoblacklight_version` to documentation and fixtures
- adds `dc_source_sm` field to documentation
- migrates the JSON-Schema definition of the GeoBlacklight schema from geoblacklight-schema repo
- improves documentation and support for auto-generation of docs (via `prmd doc geoblacklight-schema.json`) -- see https://github.com/geoblacklight/geoblacklight/blob/d01a9c1152849838ecee4d069a25c58210837961/schema/geoblacklight-schema.md
- adds the `geoblacklight:solr:ingest[directory]` rake task
NOTE that this branch *requires* you to reconfigure your jetty …
> schema changes for v1.0.0

- app/helpers/geoblacklight_helper.rb
- spec/helpers/geoblacklight_helpers_spec.rb
This PR fixes a problem with a missing "Description" value on the show page. Blacklight sends the `value` argument in as an Array that needs to be unpacked to get at the string in `render_value_as_truncate_abstract`. Not sure if this is the best fix, but I copied what `snippet` was doing already.
> handle an Array value in render_value_as_truncate_abstract helper

- lib/tasks/geoblacklight.rake
This PR fixes a typo in the default directory
> fix typo in the default directory for geoblacklight:solr:ingest task

- geoblacklight.gemspec
This PR unpins the version for the `font-awesome-rails` gem. The current version is 4.6.3.1
> unpin the version of font-awesome-rails gem

- app/models/concerns/geoblacklight/solr_document.rb
Removes  unnecessary return statements in the solr_document concern. A dinky PR, but these were bothering me.
> Remove unnecessary return statements

- schema/geoblacklight-schema.json
- schema/geoblacklight-schema.md
This PR improves the enum and pattern matching validation. It also makes `dc_format_s` a free-text field to support more file formats. This PR is connected to https://github.com/geoblacklight/geoblacklight-schema/issues/84
> Improve strictness of schema validation

- .travis.yml
- config/initializers/rails_config.rb
- geoblacklight.gemspec
- lib/geoblacklight/engine.rb
- lib/geoblacklight/view_helper_override.rb
- lib/geoblacklight/wms_layer.rb
- spec/controllers/catalog_controller_spec.rb
- spec/controllers/download_controller_spec.rb
- spec/spec_helper.rb
- spec/support/backport_test_helpers.rb
Initial experiments with rails 5 compatibility. There are 11 broken tests and a slew of deprecation warnings, but the app seems to run just fine. Here are the steps I used to get this running:
1. Start with a clean gemset and switch to the `rails-5` branch.
1. Run `RAILS_VERSION=5.0.0 bundle install`
1. Monkey patch rails to fix error with the squish method.
- Not sure what this is about, but this can be tracked down later.
- This is the [line in actionpack](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing.rb#L257) that needs to be patched.
- Find that file in your gemset. For me, this was the path:  
```
/Users/eliotj/.rvm/gems/ruby-2.2.2@r5-bl/gems/actionpack-5.0.0/lib/action_dispatch/routing.rb`
```
- Using the `gem which rails` command can help you …
> Rails 5 Compatibility 

- app/controllers/wms_controller.rb
- spec/controllers/wms_controller_spec.rb
- spec/lib/geoblacklight/wms_layer_spec.rb
Fix WMS feature inspection. ~~Rails 5 parameters are objects and need to be converted to hashes using the `to_unsafe_h` method for compatibility.~~ We have to explicitly permit WMS parameters (url, layer, bbox, etc…).
> Fix WMS feature inspection

- template.rb
Pin the geoblacklight gem version in the template file. There have been some issues with users running the `rails new` command with older versions of the gem installed.
> Pin the geoblacklight gem version in template.rb

- Rakefile
- lib/tasks/geoblacklight.rake
Improves behavior of solr server rake tasks.
- Runs `solr:seed` as part of  `geoblacklight:server`.
- Solr server shuts down in a friendly way instead of spitting out exception messages.
Closes #485.
> Improve behavior of solr server rake tasks

- .travis.yml
- geoblacklight.gemspec
Fixes an issue with installing the geoblacklight with an older version of rubygems.
- Requires a version of ruby gems greater than or equal to 2.5.2.
- Forces Travis to update rubygems to latest version.
> Rubygems update

- schema/geoblacklight-schema.json
Closes #496. This modifies the JSON schema to support geoblacklight
records containing a single layer and an array of layers.
> Support both a single layer and an array of layers

- spec/features/split_view.html.erb_spec.rb
Though I wonder if `/^1 - \d of \d$.*/`is more flexible?
> loosen up index view reset spec regex

- app/models/concerns/geoblacklight/spatial_search_behavior.rb
- lib/generators/geoblacklight/templates/settings.yml
- spec/models/concerns/geoblacklight/spatial_search_behavior_spec.rb
@mejackreed - what are your thoughts on this? Making the bq boost configurable prevents the need for local overrides, like in [EarthWorks](https://github.com/sul-dlss/earthworks/blob/00b4eb1c5ead601095d6363ba4822fe8bae1c326/app/models/search_builder.rb#L11).
> makes the bq boost value for bbox within matches configurable

- app/views/catalog/_home_text.html.erb
If a Geoblacklight application gets configured for multiple search fields the search form doesn't fit in the homepage gray jumbotron banner.
Current:
Proposed change:
> allow search bar fields to fit in homepage jumbotron

- lib/generators/geoblacklight/install_generator.rb
- template.rb
solr_wrapper is a dependency of Blacklight and gets installed as part of the Blacklight install generator. Removes redundant/unused install generator code for GeoBlacklight generator and template.
> Remove solr_wrapper from geoblacklight generator

- app/views/catalog/_search_form_no_navbar.html.erb
- lib/generators/geoblacklight/templates/catalog_controller.rb
- spec/features/empty_search_spec.rb
Closes #526. Makes the homepage search form fields behave more consistently with search results page search form: https://github.com/projectblacklight/blacklight/blob/c5b170a0a404fd97df32f80dbc47fa58d3c9c152/app/views/catalog/_search_form.html.erb
By configuring a single search field in the catalog_controller, Blacklight will submit a url `search_field` parameter, which causes the `has_search_parameters?` to return true in https://github.com/geoblacklight/geoblacklight/blob/3603575c85b81b4070d56f3011dd9b55873a2697/app/views/catalog/index.html.erb#L1 (and render the search results).
> allow blank search to retrieve full results set

- .travis.yml
- geoblacklight.gemspec
- spec/test_app_templates/lib/generators/test_app_generator.rb
This change is an effort to provide a migration path for Rails 4.2 users
as we intend to drop Rails 4.2 in the v1.6.0 release
>  reduce support for Rails >= 4.2 < 5.1 and Blacklight > 6.3 < 6.10

- lib/geoblacklight/constants.rb
Adds support for a IIIF manifest type in the external services reference hash.
> add iiif_manifest as external service type

- app/assets/javascripts/geoblacklight/modules/results.js
- app/assets/javascripts/geoblacklight/viewers/map.js
- spec/features/search_results_map_spec.rb
- spec/fixtures/solr_documents/umn_metro_result1.json
- spec/fixtures/solr_documents/umn_metro_result2.json
- spec/fixtures/solr_documents/umn_state_result1.json
- spec/fixtures/solr_documents/umn_state_result2.json
Add decimal support to parseableBbox RegExp; Thanks and HT to @nihiliad
The B1G Geoportal bounding box data attributes include decimals, ex:
"-97.991522 42.891013 -87.177541 49.892443".  As such, the 1.4.0
release parseableBbox RegExp pattern could not parse any of our bboxes.
GeoBlacklight.Viewer.Map now adds a data-js-map-render-bbox attribute
upon valid bboxes, so specs can verify search result sets render an
appropriate initial map view bbox.
> Update parseableBbox and add specs to validate map initial view

- app/presenters/geoblacklight/document_presenter.rb
This change allows html (ie links to searches, or characters like double quotes) to render in the search results view.
Example (expand the search result): https://earthworks.stanford.edu/?utf8=%E2%9C%93&q=+100+Years+of+Estuarine+Marsh+Trends
> allow search results html to render

- .travis.yml
- geoblacklight.gemspec
- spec/features/layer_inspection_spec.rb
- spec/features/split_view.html.erb_spec.rb
- spec/spec_helper.rb
Resolves #558 by addressing the following:
- Updating RSpec functional test suites to use Headless Chrome on Selenium as a test driver
- Modifying the test suites for the Index View and Layer interaction for the Selenium
> Deprecates PhantomJS for Headless Chrome

- config/locales/geoblacklight.en.yml
- lib/geoblacklight/view_helper_override.rb
- spec/features/saved_searches_spec.rb
- spec/lib/geoblacklight/view_helper_override_spec.rb
This shouldn't be a breaking change and makes it easier to configure a custom label for the bounding box search constraint.
> make bounding box constraint label configurable

- app/assets/javascripts/geoblacklight/modules/metadata_download_button.js
- app/assets/stylesheets/geoblacklight/_geoblacklight.scss
- app/assets/stylesheets/geoblacklight/modules/metadata_markup.scss
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_metadata.html.erb
- app/views/catalog/metadata/_markup.html.erb
- geoblacklight.gemspec
- lib/generators/geoblacklight/templates/settings.yml
- lib/geoblacklight/engine.rb
- lib/geoblacklight/metadata/base.rb
- lib/geoblacklight/metadata_transformer/base.rb
- spec/features/metadata_panel_spec.rb
- spec/helpers/geoblacklight_helper_spec.rb
- spec/lib/geoblacklight/metadata_transformer/base_spec.rb
- spec/lib/geoblacklight/references_spec.rb
Resolves #566 by addressing the following:
- Handling cases in which metadata can be rendered as 
XML (using CodeRay)
- Ensures that metadata retrieved using the HTTP can be offered by endpoints issuing redirect responses
- Reintroducing core support for the MODS as a metadata type
Please find the attached screenshot for the interface updates:
> Handle geospatial metadata as XML (without HTML transforms)

- geoblacklight.gemspec
- lib/geoblacklight/engine.rb
We use the third party mime-types gem in lib/geoblacklight/download.rb
but never explicitly include it or declare it as a dependency. It most
cases, it seems to still work probably because it gets included by
another gem somewhere. We shouldn't rely on this, though.
> Make sure mime-types gem is required

- geoblacklight.gemspec
- spec/spec_helper.rb
Set a window-size for Capybara tests and lock our Blacklight dependency to 6.11.0, which is the last release of BL that doesn’t exhibit the modal asset re-fetching JS bug. #569
> Fix common testsuite errors

- lib/generators/geoblacklight/install_generator.rb
- spec/routing/catalog_routing_spec.rb
Preserve OpenSearch route priority, by adding GBL routes after BL routes. This PR fixes the OpenSearch routing issue #574
> Fix OpenSearch Route Priority

- app/assets/javascripts/geoblacklight/geoblacklight.js
- app/assets/javascripts/geoblacklight/modules/util.js
- app/assets/javascripts/geoblacklight/templates/index_map_info.hbs
- app/assets/javascripts/geoblacklight/viewers/index_map.js
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_show_default_viewer_information.html.erb
- geoblacklight.gemspec
- lib/generators/geoblacklight/templates/geoblacklight.js
- lib/generators/geoblacklight/templates/geoblacklight.scss
- lib/geoblacklight/constants.rb
- lib/geoblacklight/engine.rb
- lib/geoblacklight/item_viewer.rb
- spec/features/index_map_spec.rb
- spec/features/split_view.html.erb_spec.rb
- spec/fixtures/solr_documents/index-map-stanford.json
- spec/lib/geoblacklight/item_viewer_spec.rb
- vendor/assets/javascripts/leaflet-label-src.js
- vendor/assets/stylesheets/leaflet-label.css
Closes #406 
Closes #459 
This pull request adds a custom javascript viewer for index maps referenced in a layer's `dct_references_s` field. The index map viewed is displayed using expected fields from https://github.com/OpenIndexMaps/openindexmaps.github.io/blob/master/index.md and must be an accessible GeoJSON file with `Polygon` features.
_Note:_ This pull request adds two dependencies:
- Leaflet-label (removable when we upgrade to Leaflet >= v1.0 See https://github.com/geoblacklight/geoblacklight/pull/553)
- Handlebars & handlebars assets - allows us to write clientside templates. Could be used to enhance feature inspection, metadata view, or attribute definitions
_Note:_ I did have a concern about the handlebars_assets templates precompiling in production. In my test GeoBlacklight …
> Adds index map functionality

- lib/geoblacklight/references.rb
- spec/features/download_layer_spec.rb
- spec/features/split_view.html.erb_spec.rb
- spec/lib/geoblacklight/references_spec.rb
> Ensures that the ordering of metadata formats in the config. is preserved in the ordering of metadata References for a Document

- app/helpers/geoblacklight_helper.rb
- spec/helpers/geoblacklight_helper_spec.rb
- ~~Makes `layer_geom_type_s` a required field in the GeoBlacklight schema.~~
- ~~Bumps the schema up a minor version to 1.1.~~
- Gracefully handles cases where `layer_geom_type_s` is missing in the document.
Closes #516
> Gracefully handle nil geoblacklight icon values

- lib/geoblacklight/relation/relation_response.rb
- spec/features/home_page_spec.rb
- spec/fixtures/solr_documents/uva_slug_colon.json
- spec/lib/geoblacklight/relation/relation_response_spec.rb
- spec/spec_helper.rb
Fixes issue when slugs contain characters such as the colon.
Closes #573
>  Escape relation response search id

- app/assets/stylesheets/geoblacklight/_blacklight_overrides.scss
- app/assets/stylesheets/geoblacklight/_geoblacklight.scss
Fixes #634 and includes a dedicated _blacklight_overrides.scss file to override styles inherited from Blacklight proper. This will be useful during major release upgrades and for temporarily overriding styles bugs inherited upstream.
> Add support for overriding styles inherited from Blacklight proper

- lib/generators/geoblacklight/templates/catalog_controller.rb
- spec/features/home_page_spec.rb
Fixes issue in BL7 branch where bookmarks and history links are missing from the nav bar.
Closes #638
> Add bookmarks and search history nav actions to catalog controller template

- app/assets/stylesheets/geoblacklight/modules/item.scss
- lib/generators/geoblacklight/templates/catalog_controller.rb
- spec/views/catalog/_upper_metadata.html.erb_spec.rb
Resolves #640 addressing the following:
- Restoring the styling to the metadata section on the item show page
- Replacing link_to_search (which has been deprecated) with link_to_facet for the CatalogController
Smartphone/tablet portrait viewport width:
Landscape/desktop viewport width:
> Restores the metadata formatting on item show views

- app/assets/stylesheets/geoblacklight/_blacklight_overrides.scss
- app/assets/stylesheets/geoblacklight/modules/results.scss
- app/views/catalog/_document_split.html.erb
- lib/generators/geoblacklight/templates/catalog_controller.rb
- spec/features/split_view.html.erb_spec.rb
Fixes #639 / Re-adds the sort and per_page widgets. Reorders .document child elements via flexbox's order rule. Tightens BL7 default spacing for facets and .document results, returning these GBL elements to a half-rem for spacing instead of a full rem.
> 639 search results formatting

- app/assets/javascripts/geoblacklight/modules/home.js
- app/assets/javascripts/geoblacklight/viewers/map.js
- app/assets/stylesheets/geoblacklight/modules/home.scss
Resolves #637 by addressing the following:
- Adjusting the initial bounding box for Leaflet on the home landing page
- Restoring the link color for the leaflet search control
> Restores the default bounding box for the Leaflet viewer on the landing page

- .rubocop.yml
- app/assets/stylesheets/geoblacklight/modules/metadata_content.scss
- config/locales/geoblacklight.en.yml
- lib/generators/geoblacklight/templates/settings.yml
- lib/geoblacklight.rb
- lib/geoblacklight/metadata/html.rb
- spec/fixtures/solr_documents/cornell_html_metadata.json
- spec/lib/geoblacklight/metadata/html_spec.rb
- spec/lib/geoblacklight/metadata_spec.rb
Displays HTML metadata endpoints in an iframe in the metadata modal.
Closes #624
> Add HTML metadata display

- lib/generators/geoblacklight/install_generator.rb
Sets the default application name to `GeoBlacklight`. Also added a note in the BL7 upgrade document to make sure that application name is set correctly. 
Closes #609
> Set the proper application name

- app/assets/stylesheets/geoblacklight/_geoblacklight.scss
- app/assets/stylesheets/geoblacklight/modules/relations.scss
- app/assets/stylesheets/geoblacklight/modules/sidebar.scss
- app/assets/stylesheets/geoblacklight/modules/toolbar.scss
- app/views/relation/_ancestors.html.erb
- app/views/relation/_descendants.html.erb
- app/views/relation/index.html.erb
- spec/features/relations_spec.rb
Resolves #644 by restoring the styling for the relations ("Data Relations") sidebar panel and refactoring the SCSS for the "Tools" panel:
> Restores the styling for the Data Relations sidebar panel

- app/views/catalog/_show_default_attribute_table.html.erb
Fixes issue with improperly sized feature inspection table by removing the `table-responsive` class. The table is not responsive, so it isn't needed.
Closes #645
> Remove table-responsive class to fix issue with attribute column width

- .rubocop.yml
- app/assets/javascripts/geoblacklight/downloaders/downloader.js
- app/assets/stylesheets/geoblacklight/modules/downloads.scss
- app/assets/stylesheets/geoblacklight/modules/sidebar.scss
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_show_downloads.html.erb
- app/views/catalog/_show_tools.html.erb
- config/locales/geoblacklight.en.yml
- spec/features/download_layer_spec.rb
- spec/helpers/geoblacklight_helper_spec.rb
- spec/spec_helper.rb
- spec/views/catalog/_show_downloads.html.erb_spec.rb
For smartphones/tablets/portrait viewport width:
> Adjusts the download and export panel styles for Bootstrap 4

- Gemfile
- geoblacklight.gemspec
- spec/spec_helper.rb
Closes #686 
- Sends coverage data to coveralls when using circle ci.
- Generates coverage documentation on every run of the specs.
> Refactor simplecov and coveralls

- .rubocop.yml
- app/assets/javascripts/geoblacklight/downloaders/downloader.js
- app/assets/javascripts/geoblacklight/modules/metadata.js
- app/assets/javascripts/geoblacklight/modules/metadata_download_button.js
- app/assets/stylesheets/geoblacklight/modules/home.scss
- app/assets/stylesheets/geoblacklight/modules/modal.scss
- app/assets/stylesheets/geoblacklight/modules/toolbar.scss
- app/assets/stylesheets/geoblacklight/modules/web_services.scss
- app/views/catalog/_metadata.html.erb
- app/views/catalog/metadata.html.erb
- app/views/catalog/web_services.html.erb
- app/views/download/hgl.html.erb
- spec/features/download_layer_spec.rb
- spec/javascripts/metadata_download_button_spec.js
- spec/requests/hgl_downloads_spec.rb
Resolves #642, #643, and #646  by addressing the following:
- Fixing the metadata download functionality
- Updating the nav pills on the metadata modal
- Restoring the proper styles for the metadata and web services modals
- Fixing the styling and markup for HGL downloads
> Restores web service, metadata, and HGL download modal styling

- Rakefile
Allows developers to run solr and rails server(using `rake engine_cart:server`) in seperate terminal windows. Makes development of engine easier, as developer has to only restart the server process after making changes.
Closes #658
> Add rake task to run Solr only

- geoblacklight.gemspec
Previously, attempting regenerate the app. without a fresh clone did not automatically update `simplecov`, throwing an error relating the following:
```
SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new(
[
SimpleCov::Formatter::HTMLFormatter,
Coveralls::SimpleCov::Formatter
]
)
```
This is fixed by
> Uses specific version releases for `simplecov`

- app/assets/stylesheets/geoblacklight/_styles.scss
- app/assets/stylesheets/geoblacklight/modules/downloads.scss
- app/assets/stylesheets/geoblacklight/modules/facets.scss
- app/assets/stylesheets/geoblacklight/modules/geosearch.scss
- app/assets/stylesheets/geoblacklight/modules/home.scss
- app/assets/stylesheets/geoblacklight/modules/icon-customization.scss
- app/assets/stylesheets/geoblacklight/modules/item.scss
- app/assets/stylesheets/geoblacklight/modules/layer_opacity.scss
- app/assets/stylesheets/geoblacklight/modules/metadata.scss
- app/assets/stylesheets/geoblacklight/modules/metadata_content.scss
- app/assets/stylesheets/geoblacklight/modules/metadata_markup.scss
- app/assets/stylesheets/geoblacklight/modules/mixins.scss
- app/assets/stylesheets/geoblacklight/modules/modal.scss
- app/assets/stylesheets/geoblacklight/modules/relations.scss
- app/assets/stylesheets/geoblacklight/modules/results.scss
- app/assets/stylesheets/geoblacklight/modules/sidebar.scss
- app/assets/stylesheets/geoblacklight/modules/toolbar.scss
Following Bootstrap's lead, migrate SCSS files from px to rem. Assuming standard browser 1rem = 16px base.
Vertical spacers (margins/paddings) shifted to 1 or half rem increments (ex. 6px to 0.5rem) to standardize vertical rhythm. Horizontal spacers converted directly from px to rem (ex. 12px to 0.75rem), except where within 1px to base (ex. 15px to 1rem). Hard-coded heights shifted to 16px/per rem closest fit (ex. 450px/16px = 28.125, so 28rem). Odd px counts converted to nearest divisible by 4, cuz' 16 base (ex. 5px to 0.25rem).
This is the initial conversion commit. Some polishing commits to follow.
> 675 scss from px to rems

- app/assets/stylesheets/geoblacklight/modules/downloads.scss
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_show_downloads.html.erb
- spec/features/download_layer_spec.rb
- spec/helpers/geoblacklight_helper_spec.rb
When trying to update to v1.9.0 i found myself having to override some of the scss. I wonder if using some of these default classes can help us prevent that. @jrgriffiniii what do you think?
Also updates the heading levels for accessibility compliance.
> use bootstrap styles instead of custom scss + heading levels

- app/assets/javascripts/geoblacklight/viewers/esri/dynamic_map_layer.js
Fixes #715 - New specific layer argument format fixes zero-result javascript errors. Out of map layer area map clicks will now also return the "Could not find that feature" message instead of a zero-result error. Bumping the default tolerance to 2 helps return results from very small layer markers.
Not adding or modifying tests here, as our test suite has very little coverage for our ESRI viewers. Rather, we should solve that problem elsewhere.
> Bug Fix: modify DynamicMapLayer calls to support layer specific argument

- lib/generators/geoblacklight/templates/catalog_controller.rb
- spec/features/sms_spec.rb
Resolves #734 .  Please see the following screenshots:
> Ensures that the SMS tool link is rendered by default

- spec/fixtures/solr_documents/point_index_map.json
so that the index map itself can be downloaded
> added download to dct_references

- lib/generators/geoblacklight/templates/catalog_controller.rb
Putting translations directly into catalog_controller results in the translation not being loaded upon server startup. Our "More details at" field label is the only one using I18n in the catalog_controller. All of the other labels within that file are just written directly into it: "Author(s)", "Description", etc.
In Blacklight and GeoBlacklight catalog_controller.rb files I18n translations are not used at all. Removing this sole I18n call to follow common behavior for now.
Fixes: #736
> Remove I18n call in catalog_controller.rb

- spec/teaspoon_env.rb
This PR monkey patches teaspoon to support driver_options, allowing us to set :selenium as the driver,  but use chrome driver configured via driver_options.
Teaspoon tests pass locally, but more importantly are actually run successfully by CircleCI, too.
Fixes #745
> Teaspoon: Use chromedriver via selenium

- app/models/concerns/geoblacklight/spatial_search_behavior.rb
- spec/features/search_spec.rb
- spec/fixtures/solr_documents/README.md
- spec/fixtures/solr_documents/princeton-child1.json
- spec/fixtures/solr_documents/princeton-child2.json
- spec/fixtures/solr_documents/princeton-parent.json
Adds the `suppressed_b` field to the solr doc to indicate if a record should be suppressed in the search.
Closes #737
> Add field to solr document that indicates if a record should be suppressed

- .rubocop.yml
- app/models/concerns/geoblacklight/spatial_search_behavior.rb
- lib/generators/geoblacklight/templates/settings.yml
- solr/conf/core.properties
- solr/conf/schema.xml
- solr/conf/solrconfig.xml
- spec/features/search_results_overlap_ratio_spec.rb
- spec/models/concerns/geoblacklight/spatial_search_behavior_spec.rb
This PR adds optional spatial search overlapRatio relevancy support. Configurable via the presence of Settings.OVERLAP_RATIO_BOOST.
When a bbox param is present, the Settings.OVERLAP_RATIO_BOOST value will boost results based on the overlap ratio of the result bboxes.
Includes a modification to our Solr schema to include a _bboxtype fieldtype. Requires Solr 7.4+ 
Thanks to:
@hudajkhan / Feature development
@ewlarson / Rspec tests
> Issue 324 bboxrelevancy

- .circleci/config.yml
This should ensure that failures to shut down `solr_wrapper` don't break builds for CircleCI (please see https://circleci.com/gh/geoblacklight/geoblacklight/888 for reference).
> Modifies the CircleCI configuration to use Docker containers for Solr

- .circleci/config.yml
- spec/features/esri_viewer_spec.rb
Marks a spec pending (and incorporates changes from #790) for a failure that happens also locally from an external service no longer supporting cors.
> Mark spec pending for external failure cause due to cors

- app/views/relation/_descendants.html.erb
- lib/geoblacklight/relation/relation_response.rb
- spec/features/search_spec.rb
- spec/fixtures/solr_documents/README.md
- spec/fixtures/solr_documents/princeton-child3.json
- spec/fixtures/solr_documents/princeton-child4.json
See BTAA-Geospatial-Data-Project/geoportal#120 and pulibrary/pulmap#604. Thanks for the fix @ewlarson!
Hoping to backport this.
> updates link to fix related record search

- README.md
Should we remove this? Especially if geoblacklight-docker isn't really being supported?
> Remove docker from the readme

- spec/spec_helper.rb
Otherwise the browser may not run headlessly in development environments for functional test suites.
> Ensures that Chrome is run headlessly with updates to chromedriver and selenium

- app/models/concerns/geoblacklight/spatial_search_behavior.rb
- spec/features/suppressed_records_spec.rb
Fixes #801 / Bug fix for exportable methods on suppressed documents.
CatalogController#show and CatalogController#web_services spawn different queries to Solr. The #show method queries for a single document. The #web_services method (and other exportable actions) assumes a potential array of documents.
The query syntax for an array of documents includes any applied filters and additionally appends the SpatialSearchBehavior#hide_suppressed_records filter, which causes #web_services calls on suppressed documents to 500.
This PR adds a secondary check to the hide_suppressed_records method to ensure queries for single records (likely from exportable view calls) are not filtered, so #web_services calls properly return 200. Specs added to test for successful call.
> 801 suppressed doc exportable views

- .circleci/config.yml
- geoblacklight.gemspec
- package.json
- spec/javascripts/metadata_download_button_spec.js
Also ensures that a minimal `package.json` is present (this eases the process of testing in local development environments), explicitly specifies `teaspoon` as a development dependency, and ensures that the teaspoon test suites are run on CircleCI.  Resolves #819
> Corrects the Teaspoon test fixture for metadata download buttons

- README.md
As per the discussion on #814 it is a bit confusing on launching a blank GeoBlacklight app from the template versus launching one that has fixture records indexed in it. I made a few small tweaks here to make it clearer and will update a couple things on the Wiki as well
> makes small changes on readMe file

- app/assets/javascripts/geoblacklight/modules/help_text.js
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_show_default_viewer_container.html.erb
- config/locales/geoblacklight.en.yml
- lib/generators/geoblacklight/templates/settings.yml
- spec/features/help_text_spec.rb
- spec/helpers/geoblacklight_helper_spec.rb
This WIP branch adds support for a generic help text feature. The help text feature can be added or removed from the GBL Settings file to toggle help text display.
```yaml
HELP_TEXT:
viewer_protocol:
- 'dynamic_map_layer'
- 'feature_layer'
- 'iiif'
- 'iiif_manifest'
- 'image_map_layer'
- 'index_map'
- 'tiled_map_layer'
- 'wms'
```
The :en locale file defines the help text displayed.
```yaml
help_text:
viewer_protocol:
dynamic_map_layer:
title: ArcGIS Dynamic Map Layer
content: An ArcGIS Dynamic Map Layer is based on vector data. (points, lines, and polygons). Map image layers are dynamically rendered image tiles. Click on a feature to view attribute information.
```
And, two new GBL helpers allow to check a feature for help text and render its display.
```ruby
// Pass the "feature" and …
```
> Add help text feature

- app/helpers/geoblacklight_helper.rb
Previously, the `#asset_exists?` method relies on Sprockets development
mode. This will fail when moved into production. The modification here
just relies on Blacklight's exception that is raised when it cannot find
the asset.
> Fixes #851 by relying on blacklight_icons raise if file not found

- .circleci/config.yml
- .rubocop_todo.yml
- Gemfile
- spec/features/esri_viewer_spec.rb
- spec/features/split_view.html.erb_spec.rb
- spec/lib/geoblacklight/wms_layer_spec.rb
This handful of commits makes our test suite run successfully on CircleCI again:
-  Bump our ruby versions to latest minor versions with node
-  Enable an ESRI pending test that passes now
-  Change a facet spec from click_link to a click_button
-  Update Faraday Error messages for WMS errors
-  Add a Gemfile sass-rails rule for Rails 5 to 6
-  Remove old cops from our rubocop_todo file
Fixes #864  
Might also solve #866
> Makes CircleCI happy again

- .circleci/config.yml
- Gemfile
- lib/generators/geoblacklight/install_generator.rb
- spec/test_app_templates/Gemfile.extra
Advances #866 and #789 
- Updating the structure of the CircleCI config. to test against Ruby 2.6.z and 2.5.z releases along with Rails 5.1.z and 5.2.z releases
- Ensuring that sass-rails 6.0.z releases are used when generating Rails 5.1.z and 5.2.z apps
- Removing support for Rails 4.y.z releases from the Gemfile
> Updating the structure of the CircleCI config. to test against Ruby 2.6.z and 2.5.z releases

- solr/conf/schema.xml
From Solr docs: "Copying is done at the stream source level and no copy feeds into another copy. This means that copy fields cannot be chained i.e. you cannot copy from here to there and then from there to elsewhere."
So! copying into a dynamically created wildcard field doesn't allow us to then "chain" that new dynamic field value to populate the "text" field.
Switch to using *_s and *_sm fields to ensure our "catch all" field is properly populated.
Fixes #857
> Bug Fix: update copyField statements for "catch all" search field

- .circleci/config.yml
- lib/geoblacklight/catalog_helper_override.rb
- lib/geoblacklight/view_helper_override.rb
2e90cde8c48c1cbc48a0d07aaf3f2b3eca36da76 busts the cache for the circle-ci builds. We probably want to revisit this at some point.
Fixes #895
> Use modern node-browsers for circle-ci + Blacklight v7.8.0 fixes to fix build

- app/views/catalog/_web_services_wfs.html.erb
- app/views/catalog/_web_services_wms.html.erb
(also update the bootstrap classes for improved styling)
Closes sul-dlss/earthworks#642
I can't speak to the usage of `readonly` form elements here, but it looks like it has been that way since this feature was implemented.
> Add a for/id attribute on the wfs/wms specific web services partials.

- app/helpers/geoblacklight_helper.rb
- app/views/relation/_ancestors.html.erb
- app/views/relation/_descendants.html.erb
- lib/generators/geoblacklight/templates/settings.yml
- lib/geoblacklight/relation/ancestors.rb
- lib/geoblacklight/relation/descendants.rb
- spec/features/relations_spec.rb
- spec/helpers/geoblacklight_helper_spec.rb
- spec/lib/geoblacklight/relation/ancestors_spec.rb
- spec/lib/geoblacklight/relation/descendants_spec.rb
fixes #907
This has been enabled in a backwards compatible way so that adopters wanting to use the static leaf icons still can do so.
> Enable data relations widget to use icons from the related item 

- app/assets/javascripts/geoblacklight/modules/collapse.js
- app/assets/stylesheets/geoblacklight/modules/results.scss
- app/views/catalog/_index_split_default.html.erb
- spec/features/split_view.html.erb_spec.rb
- Use bootstrap collapse to handle collapsing
- Make the collapse toggle a button
- Use flexbox for truncation
Addresses part of https://github.com/sul-dlss/earthworks/issues/687
> Redo the search results display to be accessible

- lib/tasks/geoblacklight.rake
- spec/tasks/geoblacklight_spec.rb
- Removes unnecessary Dir.glob() call.
- Adds a test case (spec/tasks/geoblacklight.rake). This test case fails
with the original code.
> Fix geoblacklight:downloads:mkdir task

- .circleci/config.yml
Closes #905 
Will continue to work to improve CI run time after this is merged.
> Remove parallel specs and reduce number of rubocop runs

- app/models/concerns/geoblacklight/spatial_search_behavior.rb
- spec/models/concerns/geoblacklight/spatial_search_behavior_spec.rb
Fixes #894 - This allows local default solr params to remain included in the final solr query.
> SpatialSearch: append boost instead of setting via hard assignment

- app/assets/javascripts/geoblacklight/viewers/esri/tiled_map_layer.js
- spec/javascripts/geoblacklight/viewers/esri/tiled_map_layer_spec.js
closes #936 
Update tiled_map_layer not to include nested namespace L.esri.Tasks
This was updated in esri-leaflet 2.0.0-beta.4
Release notes https://github.com/Esri/esri-leaflet/blob/542022a2f216b7ad43471876a693a0257e92582d/CHANGELOG.md#breaking-1
Relevant specs https://github.com/esri/esri-leaflet/compare/v2.0.0-beta.3...v2.0.0-beta.4#diff-06cb9def3f931de1e3006a21cb9fbae3L38-L39
> Fixes bug in tiled_map_layer

- .circleci/config.yml
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_arcgis.html.erb
- app/views/catalog/_carto.html.erb
- app/views/catalog/_exports.html.erb
- lib/generators/geoblacklight/templates/catalog_controller.rb
- lib/generators/geoblacklight/templates/settings.yml
- spec/features/exports_spec.rb
A breaking change building on https://github.com/geoblacklight/geoblacklight/pull/837 which does things more like Blacklight would expect for configuring the display of a show tools partial. Rather than having our own setting in GeoBlacklight, just use the configurability that Blacklight gives us.
> Breakout individual tools into their own show tools configuration

- .gitignore
- app/views/catalog/_home_text.html.erb
- config/locales/geoblacklight.en.yml
This PR addresses #853 and exposes the current GeoBlacklight version running on the app homepage. It references the value present in the `lib/geoblacklight/version.rb` file. 
This PR also adds `.DS_Store` to the `.gitignore` file in the project
> adds version number to homepage

- app/assets/stylesheets/geoblacklight/_styles.scss
- app/assets/stylesheets/geoblacklight/modules/item.scss
This PR address two styling issues:
- The maps on the item show page don't have borders, which feel a little odd given they are so close to other page elements that do have borders (sidebar cards), and generally they would just feel more defined on the page with a subtle border (which is easy to override locally for implementers that don't want it).
- For the WMS maps, the table is jammed up directly against the bottom of the map. Perhaps this was intentional -- because selections on the map directly affect the contents of the table -- but as a relatively new GeoBlacklight user I found this confusing; for a while I thought the map and table were some kind of  single element.
Here are those two issues as seen in current `master`:
---
And here is how this PR changes them:
> Add border to item map and space between it and WMS table

- app/assets/stylesheets/geoblacklight/modules/downloads.scss
- app/assets/stylesheets/geoblacklight/modules/relations.scss
- app/assets/stylesheets/geoblacklight/modules/sidebar.scss
- app/assets/stylesheets/geoblacklight/modules/toolbar.scss
This PR updates the item show page sidebar styling, with two main goals:
* Improve consistency of element spacing within the sidebar cards and reduce excess vertical whitespace to make overall sidebar more compact
* Refactor and simplify the sidebar-related SCSS files to make it easier to maintain styling consistency and do local overrides
As discussed with @mejackreed, this PR shouldn't be considered until the next major release. The updates look good on all of the 35 test fixtures (tested on Firefox, Safari, and Chrome on MacOS, not tested on Windows) but might break existing local customizations to the sidebar styling.
Further visual and SCSS simplification could be done if the suggestions (https://github.com/sul-dlss/earthworks/issues/646)  for how we present the Download and Export …
> Improve consistency of sidebar styling and refactor relevant SCSS

- app/assets/stylesheets/geoblacklight/_geoblacklight.scss
- app/assets/stylesheets/geoblacklight/modules/relations.scss
- app/views/relation/_ancestors.html.erb
- app/views/relation/_descendants.html.erb
- app/views/relation/index.html.erb
- config/locales/geoblacklight.en.yml
- spec/features/relations_spec.rb
- spec/spec_helper.rb
Part of #906 
Part of #909 
This also removed the custom relations css module to adopt something closer to the Blacklight approach for styling cards.
> Split Data Relations card into separate cards for ancestors/descendants 

- .circleci/config.yml
- README.md
- app/helpers/geoblacklight_helper.rb
- spec/spec_helper.rb
- Bring our code coverage up to 100%.
- Since we're not using Coveralls now (and haven't for awhile), replaces the dynamically created badge for a static badge.
- If we set code coverage to enforce 100% always, then this won't need to be updated.
- If we want it to be dynamic in the future, there's a gem that can generate this for us in our CI process.
- The badge doesn't link out anywhere now, but once I figure out how to get the latest CI artifacts it could link out to Circle. https://3950-21216322-gh.circle-artifacts.com/0/coverage/index.html#_AllFiles
Closes #961
> 100 percent coverage

- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_downloads_primary.html.erb
- spec/features/multiple_downloads_spec.rb
- spec/features/search_results_overlap_ratio_spec.rb
- spec/fixtures/solr_documents/multiple-downloads.json
- spec/helpers/geoblacklight_helper_spec.rb
This pull request aims to fix #340 in the most backwards compatible way possible. While great work has happened in investigating alternatives to this approach (#884, #882, #846) I'm wondering if this helps us unblock the way forward so that a feature like this can be used without a large data migration.
This aims to accomplish the goal using the simplest means possible. While it does not accomplish some of the previous goals of using a now serialized JSON for the dct_references_s, I'm hoping it is a useful feature to adopters.
dct_references_s now can take an array as a value for `http://schema.org/downloadUrl`. That ends up looking like this (unescaped):
```json
{
"http://schema.org/downloadUrl": [
{
"url": "https://cugir-data.s3.amazonaws.com/00/79/50/cugir-007950.zip",
"label": …
```
> Add support for multiple downloads using current dct_references_s approach

- app/assets/javascripts/geoblacklight/viewers/wms.js
- lib/geoblacklight/download/kmz_download.rb
Issue #897 Testing effects of change from CRS:900913 to CRS:3857 on service calls.
Use Chrome developer tools to see if this protocol change breaks any existing layers. I inspected layers in the console by navigating to the Network Tab. Records detail which CRS request is passed and if it is successful. It is believed that this will not break any existing records.
> changing crs protocol

- app/assets/stylesheets/geoblacklight/modules/_blacklight_overrides.scss
This fixes a syntax error in `_blacklight_overrides.scss`, a missing semicolon that breaks the application when using sass-rails ~> 5.0. This might not be an issue for most people, since sassc-rails (and/or sass-rails 6.0) seems to handle missing semicolons more gracefully. We encountered it in the midst of upgrading from an earlier version of GeoBlacklight, so hopefully this will save other folks some debugging time.
> Fix syntax in _blacklight_overrides.css

- app/views/catalog/_home_text.html.erb
applications will likely want custom styles for the geoblacklight version text. this gives them a hook for customization.
> add <div> id for geoblacklight version text

- app/assets/javascripts/geoblacklight/viewers/tms.js
- config/locales/geoblacklight.en.yml
- lib/generators/geoblacklight/templates/settings.yml
- lib/geoblacklight/constants.rb
- lib/geoblacklight/item_viewer.rb
- spec/features/split_view.html.erb_spec.rb
- spec/features/tms_spec.rb
- spec/fixtures/solr_documents/tms.json
- spec/lib/geoblacklight/item_viewer_spec.rb
In place of #1016
TMS layers would be specified like this:
```
"https://wiki.osgeo.org/wiki/Tile_Map_Service_Specification":"https://earthquake.usgs.gov/basemap/tiles/faults/{z}/{x}/{y}.png"
```
This allows you to modify the tile pattern if need be.
> Adds support for a TMS viewer

- app/assets/javascripts/geoblacklight/modules/bookmarks.js
- app/assets/stylesheets/geoblacklight/modules/results.scss
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_document_split.html.erb
- spec/helpers/geoblacklight_helper_spec.rb
Fixes #246
Adds a new JS map for the bookmarks controller, removing the search features of the search results map. Sets the data-map attribute value via a new GBL helper to initialize the proper JS map on page load. Includes specs to test new helper.
With search feature.
Without search feature.
> Bookmarks: remove search functionality from bookmarks js map

- app/views/download/hgl.html.erb
> Improve layout of HGL download partial

- Rakefile
Jest tests were not running on github actions CI:
```
yarn run v1.22.5
$ jest -c jest.config.js
/bin/sh: 1: jest: not found
error Command failed with exit code 127.
```
The solution is to force running the command with bash instead of sh (https://github.com/yarnpkg/yarn/issues/6686)
> Use bash to run yarn test command

- .github/workflows/ruby.yml
- lib/geoblacklight/geometry.rb
- spec/lib/geoblacklight/geometry_spec.rb
Closes #1042 
My comment from the ticket:
> The underlying issue here, is that the envelopes / bounding boxes should be valid polygons. The most important reason is to enable a valid solr spatial search with the record. Perhaps we should add some validation to the envelope in GeoCombine. That being said, invalid polygon geometry should not prevent record display in GeoBlacklight. After doing some reading and experimentation, I've come to understand that this is a bit of a tricky issue. As far as I can tell, the problem is the underlying version of libgeos, which can be different between machines. For example, I can't replicate this directly on my development laptop. Everything works as it should. I'll work up a patch that tests the error indirectly and let's see if it fixes the problem.
> Provide a more graceful fallback for non-parsable geometry

- lib/geoblacklight/geometry.rb
- spec/lib/geoblacklight/geometry_spec.rb
Closes #1042 
Provides a default extent value when there is an error parsing a geometry or transforming into GeoJSON.
> Return default GeoJSON extent on error

- lib/geoblacklight/view_helper_override.rb
Fixes #1068
Addresses:
DEPRECATION WARNING: Use SearchState#to_h instead of SearchState#to_unsafe_h. (called from render_constraints_filters at /Users/ewlarson/Rails/geoblacklight/lib/geoblacklight/view_helper_override.rb:30)
> Deprecation Fix - Use SearchState#to_h instead of SearchState#to_unsafe_h

- app/views/catalog/_show_header_default.html.erb
Swap document_heading for document_presenter.
Fixes #1070
Co-Authored-By: Chris Beer <chris@cbeer.info>
> Deprecation Fix - document_heading

- .rubocop_todo.yml
- app/helpers/geoblacklight/geoblacklight_helper_behavior.rb
- lib/geoblacklight.rb
- lib/geoblacklight/geoblacklight_helper_behavior.rb
- spec/features/esri_viewer_spec.rb
- spec/features/layer_opacity_spec.rb
- spec/helpers/geoblacklight/geoblacklight_helper_behavior_spec.rb
Fixes #1067 
Moves GeoBlacklightHelperBehavior from lib to app/helpers, which is better aligned with Blacklight's HelperBehavior files, and allows us to include Blacklight::BlacklightHelperBehavior to access the document_presenter method.
Also adds skips for specs that reference Purdue ArcGIS web services, which are returning CORS errors at the moment.
> Deprecation Fix - presenter

- app/assets/stylesheets/geoblacklight/modules/icon-customization.scss
- app/assets/stylesheets/geoblacklight/modules/toolbar.scss
- app/views/catalog/_arcgis.html.erb
- app/views/catalog/_data_dictionary.html.erb
- app/views/catalog/_document_action.html.erb
To resolve two deprecation warnings (document_action_path and document_action_label), instead of overriding Blacklight's document actions partial and component render flow, we'll use decorative CSS-based icons for actions.
In the future, we should work to add icon support to BL's _document_action partial/component.
Fixes #1071, #1072
> Deprecation Fix - CSS-based icons for document actions

- .rubocop_todo.yml
- app/components/geoblacklight/homepage_feature_facet_component.html.erb
- app/components/geoblacklight/homepage_feature_facet_component.rb
- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_facet_tag_item.html.erb
- app/views/catalog/_facet_tag_layout.html.erb
- app/views/catalog/_home_text.html.erb
- geoblacklight.gemspec
- spec/components/geoblacklight/homepage_feature_facet_component_spec.rb
- spec/spec_helper.rb
- spec/support/view_component_capybara_test_helpers.rb
Removes our GBL render_facet_tags helper, which called deprecated methods from BL (render_facet_limit, facets_from_request). Replaces the helper with our first GBL ViewComponent component: Geoblacklight::HomepageFeatureFacetComponent
This new component renders each homepage feature facet block, including: icon, label, facet links, and the more link.
Fixes #1065, #1066
> Deprecation Fix - Convert render_facet_tags to component

- lib/generators/geoblacklight/templates/catalog_controller.rb
Improves the default sorting options by adding directional options for Year and Title: 
Year (Newest first)
Year (Oldest first)
Title (A-Z)
Title (Z-A) 
Removes the Publisher sort option as less desirable.
Fixes #1051
> Improve default sorting options

- app/helpers/geoblacklight_helper.rb
- app/views/catalog/_downloads_primary.html.erb
- spec/helpers/geoblacklight_helper_spec.rb
Removes the deprecated `download_link_direct` GBL helper method. Shifts the last usage to the preferred `download_link_file` helper method.
Fixes #1095
> Deprecation Fix - download_link_direct

- app/views/catalog/_downloads_primary.html.erb
- spec/features/show_page_download_spec.rb
Fixes #1103 and adds better feature specs for the download view partial
> Bug fix: when download is a string, just render that string for the link

- app/assets/javascripts/geoblacklight/viewers/tilejson.js
- app/assets/javascripts/geoblacklight/viewers/wmts.js
- config/locales/geoblacklight.en.yml
- geoblacklight.gemspec
- lib/generators/geoblacklight/templates/settings.yml
- lib/geoblacklight/constants.rb
- lib/geoblacklight/item_viewer.rb
- spec/features/home_page_spec.rb
- spec/features/tilejson_spec.rb
- spec/features/web_services_modal_spec.rb
- spec/features/wmts_spec.rb
- spec/fixtures/manifests/tilejson.json
- spec/fixtures/manifests/wmts-multiple.xml
- spec/fixtures/manifests/wmts-single.xml
- spec/fixtures/solr_documents/princeton-georeferenced-mapset.json
- spec/fixtures/solr_documents/tilejson.json
- spec/fixtures/solr_documents/tms.json
- spec/fixtures/solr_documents/wmts-multiple.json
- spec/fixtures/solr_documents/wmts-single-layer.json
- spec/spec_helper.rb
- Adds TileJSON viewer
- Adds WMTS viewer
- Use WebMock gem to mock WMTS and TileJSON manifest requests.
Closes #1129
> Add a viewer for TileJSON and WMTS endpoints

- app/assets/javascripts/geoblacklight/viewers/esri.js
- spec/features/esri_viewer_spec.rb
Closes #1142 
Fixes CI.
Opened a ticket to investigate better testing for ESRI viewers.
https://github.com/geoblacklight/geoblacklight/issues/1144
> Disable ESRI Specs

- spec/features/search_results_map_spec.rb
- spec/spec_helper.rb
This change made a pending test wait for a very long time and hold up the suite run time, so I disabled it
closes #1149
> Ensure webmock doesn't open endless file sockets

- app/assets/stylesheets/geoblacklight/modules/index_maps.scss
- lib/generators/geoblacklight/templates/settings.gbl_v1.yml
- lib/generators/geoblacklight/templates/settings.yml
- spec/features/index_map_spec.rb
**Updated index map colors to an accessible color palette**
* * *
**Issue**: 
* #1137 
Incorporates new accessible color palette for leaflet index maps.
Test case: http://localhost:3000/catalog/stanford-fb897vt9938
The interactive paths on index maps will now have the following:
* Black stroke color around every tile path
* Fill-opacity of each tile is now darker (from 0.2 to 0.65), but you can still see outlines/words on the map underneath the colors
* Default color (used to be green): #7FCDBB
* Unavailable color (used to be red): #EDF8B1
* Selected color (used to be blue): #2C7FB8 (still blue, just a different shade)
Notes: 
* If curious, the accessibility tool for firefox has a [color blind simulator](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector/Simulation) to …
> Updated index map colors to an accessible color palette

- solr/conf/schema.xml
- spec/features/search_spec.rb
- spec/fixtures/solr_documents/umn_metro_result1.json
This PR adds a small fixture change and a couple specs to test that multivalued year sorting does indeed work. It also adds the `sortMissingLast=true` option to *_im dynamic fields in our Solr schema.xml file. Aardvark only has one *_im field: gbl_indexYear_im.
Closes #1045
> Multivalued year sorting: specs and schema change to sort missing values last

- .github/workflows/ruby.yml
Otherwise, if the build fails because the coverage is too low, the coverage step is skipped and the artifacts aren't published.
> Always publish coverage data

- app/assets/stylesheets/geoblacklight/modules/index_maps.scss
- app/views/catalog/_show_default_viewer_container.html.erb
**Create index map legend to indicate what each color means**
* * *
**Issue**: 
* #1156 
Incorporates a static legend above index map to indicate what each tile color means.
Test case (index map): http://localhost:3000/catalog/stanford-fb897vt9938
Test case (non-index map for comparison): http://localhost:3000/catalog/stanford-dp018hs9766
* A legend should appear above index maps but not appear above any other type of map (added opacity to the colors to more closely resemble what see on the map)
- Default (green): Map held by collection
- Unavailable (yellow): Map not held by collection
- Selected (blue): Selected map tile
Screenshots demonstrating responsiveness:
Screenshot of legend with opacity applied
> Create index map legend to indicate what each color means

- lib/generators/geoblacklight/templates/assets/_customizations.scss
**Color contrast adjustments**
* * *
**Issue**: 
* #1137 
Updated :root color variables to match Bootstrap 5 colors, which has bumped their color contrast ratio from 3:1 to 4.5:1 and updated blue, green, cyan, and pink colors to ensure WCAG 2.1 AA contrast.
Test case (though any page is fine to test with): http://localhost:3000/catalog/stanford-cg357zz0321
* Using inspect you can scroll to the bottom of the styles to find the :root variables. The updated colors are as follows
```
:root {
--blue: #0d6efd;
--pink: #d63384;
--green: #198754;
--cyan: #0dcaf0;
--dark: #212529;
}
```
Note: the one remaining contrast error has to do with the linked logo because it thinks it is a blue link on gray background. Also, text that is part of a logo or brand name has no contrast requirement, so it can …
> Color contrast adjustments

- lib/generators/geoblacklight/templates/catalog_controller.rb
- spec/features/show_page_metadata_spec.rb
This branch:
1. Cleans up the ITEM VIEW FIELDS. There were some duplicated lines in the commented-out code.
2. Turns on all of the descriptive/ string value fields by default
3. Re-orders the fields to match the Aardvark schema order.
Addresses #1052 In the previous version, we had been more conservative about only showing a few fields. However, I think it is better to display them all by default. This allows adopters to evaluate the fields and the examples shown in the fixtures. It would be easier for adopters to see extraneous fields and hide them rather than not know they existed.
> Update item view fields on catalog_controller.rb

- spec/fixtures/solr_documents/actual-raster1.json
- spec/fixtures/solr_documents/cornell_html_metadata.json
- spec/fixtures/solr_documents/esri-dynamic-layer-all-layers.json
- spec/fixtures/solr_documents/esri-dynamic-layer-single-layer.json
- spec/fixtures/solr_documents/esri-image-map-layer.json
- spec/fixtures/solr_documents/harvard_raster.json
- spec/fixtures/solr_documents/index_map_point.json
- spec/fixtures/solr_documents/no_spatial.json
- spec/fixtures/solr_documents/tilejson.json
- spec/fixtures/solr_documents/umn_metro_result1.json
- spec/fixtures/solr_documents/umn_state_result1.json
- spec/fixtures/solr_documents/umn_state_result2.json
- spec/fixtures/solr_documents/wmts-single-layer.json
- spec/fixtures/solr_documents/xyz.json
This fixes a capitalization issue and changes the spellings of the Themes to match the Aardvard recommendations.
> Minor updates to Fixtures

- app/assets/stylesheets/geoblacklight/modules/downloads.scss
- app/assets/stylesheets/geoblacklight/modules/modal.scss
- app/views/catalog/_show_sidebar.html.erb
- app/views/catalog/_show_web_services.html.erb
- app/views/catalog/_web_services.html.erb
- app/views/catalog/web_services.html.erb
- lib/generators/geoblacklight/templates/catalog_controller.rb
- spec/features/web_services_modal_spec.rb
Moves the web services link to give it visual symmetry with the download button, since they serve similar use cases (namely, using the data).
It also updates the web services modal to remove a trailing line separator.
If you take no action (on an unmodified geoblacklight instance) you will have both web services links. To remove the link from the tool versions and keep the new button working:
* In your app's catalog controller
* Remove the line beginning `config.add_show_tools_partial :web_services`
* Add a small controller action to keep the web services modal working. This code was previously generated as part of blacklight's `add_show_tools_partial` functionality. The method you need can be copied from the updated catalog controller template and is called `web_services`.
> Move web services link out of show tools to a button

- .github/workflows/ruby.yml
- geoblacklight.gemspec
* Collapse extra rails 6 job into include
* Specify bundler version in matrix
* Include matrix versions in job names
* Change rails versions in gemspec to match tested versions
See #1177
I'm a little unfamiliar with bundler dependency syntax, but I think this more accurately captures what we want to test/say we support.
- We allowed Rails 5 in the gemspec, but didn't test it. Testing it failed, so I don't think we should support it.
- There was some stuff related to testing Rails 7, but our required version of Blacklight doesn't support it, so we can't support it. I think it wasn't actually getting used because the environment variable wasn't named correctly (?)
> Adjust GitHub actions matrix build

- app/models/concerns/geoblacklight/suppressed_records_search_behavior.rb
- config/locales/geoblacklight.en.yml
- lib/generators/geoblacklight/templates/catalog_controller.rb
- lib/generators/geoblacklight/templates/settings.yml
- spec/features/relations_spec.rb
- spec/fixtures/solr_documents/b1g_wabash_child_15.json
- spec/fixtures/solr_documents/b1g_wabash_child_16.json
- spec/fixtures/solr_documents/b1g_wabash_child_17.json
- spec/fixtures/solr_documents/b1g_wabash_child_18.json
- spec/fixtures/solr_documents/b1g_wabash_parent.json
We need to allow all the new Aardvark relationship fields to bypass our suppressed records filter. This PR adds additional non-Source field relationship fixtures (the Wabash Topo docs) and a feature test to ensure our "Browse all X" link is working correctly.
Fixes #1221
> Bug fix: allow all Aardvark relationship fields to browse suppressed records

- .rubocop.yml
- config/locales/geoblacklight.en.yml
- lib/geoblacklight/download.rb
- lib/geoblacklight/metadata_transformer/base.rb
- spec/controllers/catalog_controller_spec.rb
- spec/controllers/download_controller_spec.rb
- spec/controllers/relation_controller_spec.rb
- spec/helpers/geoblacklight_helper_spec.rb
I18n add: `export_geotiff_link: 'GeoTIFF'`
Fixes #1233
> I18n: fix missing GeoTIFF file download translation

- .github/workflows/ruby.yml
Latest capybara release requires Ruby 2.7 minimum. Bumping our matrix requirement to match.
> GitHub Actions: Bump Ruby to 2.7

- spec/fixtures/solr_documents/display-note.json
This adds a test record for the new Display Note field as described in #1274
> add displayNote test record

- schema/geoblacklight-schema-aardvark.json
I also made this change in the JSON validation file stored on the OpenGeoMetadata site (https://github.com/OpenGeoMetadata/opengeometadata.github.io/tree/main/schema).
Related question: is there a reason why there are two copies of these validation files?
> add `gbl_displayNote_sm` to validation file

- .github/workflows/ruby.yml
- geoblacklight.gemspec
I saw some dependency conflicts involving faraday, and so tried letting bundler update itself to newer versions to see if that would resolve them. It did, except for the odd case of trying to build native extensions for `patron`, which is a downstream dependency of faraday 1.x and needs some headers that apparently aren't on GitHub CI runners (see https://github.com/actions/runner-images/issues/37). This problem only affects faraday 1.x builds.
> Update GeoCombine to v0.8.0

- config/initializers/new_gbl_settings_defaults_3_4.yml
- config/initializers/new_gbl_settings_defaults_4.1.yml
- config/initializers/rails_config.rb
- spec/config/initializers/rails_config_spec.rb
This will help keep the v4+ upgrade path as smooth as possible.
Also, this drops the old v3.4 settings file additions. We only need v4 updates here.
> Settings: prepend the new v4.1 settings.yml additions

- .github/workflows/ruby.yml
- Gemfile
- geoblacklight.gemspec
- lib/generators/geoblacklight/install_generator.rb
- lib/generators/geoblacklight/templates/catalog_controller.rb
- lib/geoblacklight/faraday_middleware/follow_redirects.rb
- lib/geoblacklight/metadata_transformer/base.rb
- spec/features/search_results_map_spec.rb
- spec/spec_helper.rb
- spec/test_app_templates/lib/generators/test_app_generator.rb
Closes #1320  - Recent BL versions have fixed this.
Closes #1324 
Closes #1321
- Allow more recent versions of Blacklight
- Remove webpacker from test app
- Fix linting errors
- Allow and test Rails 7.1
- Drop ruby 2 and add ruby 3.3
- Test latest Rails 6.1
@geoblacklight/geoblacklight-developers
> Allow more recent versions of Blacklight and update CI testing matrix

- .github/workflows/ruby.yml
- geoblacklight.gemspec
- spec/test_app_templates/Gemfile.extra
This PR removes official support for Faraday v1 from future GeoBlacklight v4 releases.
Fixes #1334
> Drop Faraday v1

- README.md
Moves installation info out from the README and points to the external documentation on the geoblacklight website. Our main goal with this change to avoid having the same content/instructions in two different places (here and also in the external documentation).
Closes #1345
> update readme to point to external docs #1345

- app/views/catalog/_citation.html.erb
- app/views/catalog/_web_services_default.html.erb
- app/views/catalog/_web_services_wfs.html.erb
- app/views/catalog/_web_services_wms.html.erb
- app/views/catalog/web_services.html.erb
- config/locales/geoblacklight.en.yml
- spec/features/web_services_modal_spec.rb
Adds a copy to the clipboard feature for our Web services to match our "Copy citation" feature.
* The web service URL is copy-able
* The layer id is too
Fixes #1209
> Web services: add copy to clipboard feature

- geoblacklight.gemspec
This version adds some logging and speeds up harvesting/indexing from OpenGeoMetadata, as well as making the automated v1 -> Aardvark migrator available.
> Bump GeoCombine dependency to v0.9

- .github/workflows/ruby.yml
- app/frontend/entrypoints/application.js
- app/frontend/openlayers/ol_initializer.js
- app/frontend/stylesheets/openlayers.css
- app/helpers/geoblacklight/application_helper.rb
- lib/generators/geoblacklight/install_generator.rb
- lib/generators/geoblacklight/templates/clover.js
- lib/generators/geoblacklight/templates/ol.js
- lib/generators/geoblacklight/templates/package.json
- lib/generators/geoblacklight/templates/vite.config.ts
- lib/generators/geoblacklight/templates/vite.rb
- lib/geoblacklight/engine.rb
- spec/test_app_templates/lib/generators/test_app_generator.rb
Uses vite.config.ts resolve[:alias] to provide path to Rails engine code.
Addresses #1352
> Vite: uses local application entrypoints with an aliased path for importing engine code

- config/locales/geoblacklight.en.yml
- lib/generators/geoblacklight/templates/settings.yml
Adds help text entries for the newer viewer types:
* Tiled Map Layer
* TileJSON
* TMS
* WMTS
* XYZ
> Help Text: Include help text for all JS viewer types

- app/components/geoblacklight/iiif_drag_drop_component.rb
- app/components/geoblacklight/viewer_container_component.html.erb
- spec/components/geoblacklight/iiif_drag_drop_component_spec.rb
Lack of knowledge about how IIIF worked in geoblacklight. As I have gotten more into this I realize there is a field we can check for IIIF manifest not having to use the helper.
Adds manifest icon to http://localhost:3000/catalog/princeton-fk4544658v-tilejson and http://localhost:3000/catalog/princeton-fk4544658v-wmts
> show drag and drop on all items with iiif manifest

- app/controllers/download_controller.rb
Fixes #1397 - use `flash.now` instead of `flash` when rendering from an action (and not redirecting).  See https://www.rubyguides.com/2019/11/rails-flash-messages/
This ensures the message is only shown in the first render and not again.
> use flash.now instead of flash when rendering

- app/components/geoblacklight/header_icons_component.rb
- app/helpers/geoblacklight_helper.rb
- spec/features/search_results_icons_spec.rb
Closes https://github.com/sul-dlss/earthworks/issues/1045
Closes https://github.com/geoblacklight/geoblacklight/issues/1402
Before search results | After search results
After collection data with Settings.USE_GEOM_FOR_RELATIONS_ICON = true and Settings.FIELDS.GEOM_TYPE = 'gbl_resourceType_sm'
> add more specific icons for dataset docs

- lib/generators/geoblacklight/templates/settings.yml
Closes: https://github.com/geoblacklight/geoblacklight/issues/1403
Large files (like the shapefile for https://earthworks.stanford.edu/catalog/stanford-kr064yh0964, which is over 700 MB) take a long time to be generated by the geoserver.  See https://github.com/sul-dlss/earthworks/issues/272  The default timeout of 16 seconds is too short (that file takes nearly 2 minutes to generate).  This bumps the default timeout much higher, which allows it to work.
I'd recommend we should separately
1. provide some user indication that something is happening -- even at 16 seconds, it's a long time after clicking a link to get the alert telling you the download is ready.  For two minutes, people will definitely think nothing has happened.
2. perhaps try to prevent a user from clicking the link twice …
> increase timeout for downloads

- app/controllers/download_controller.rb
- app/javascript/controllers/downloads_controller.js
- spec/features/download_layer_spec.rb
(replaces #1417 which was borked due to a rebase)
Download specs are not working correctly in the modernize-js branch due to changes in the javascript from https://github.com/geoblacklight/geoblacklight/pull/1409
This fixes them.
> fix download specs

- spec/components/geoblacklight/viewer_container_component_spec.rb
This removes some RSpec warnings about how the mocking was being
done, and reduces a bit of duplication.
> Simplify a component spec

- geoblacklight.gemspec
- spec/features/split_view.html.erb_spec.rb
- spec/spec_helper.rb
This removes the custom Selenium configuration, since it didn't seem to affect the vast majority of the tests and included some complex options (huge window size, long timeouts, etc.) that made local testing harder.
It also stops using database cleaner, since transactional fixtures work just as well.
> Update testing configuration

- app/assets/stylesheets/geoblacklight/modules/item.scss
- app/javascript/controllers/clover_viewer_controller.js
Setting a page-relative height with !important caused these viewers to be much larger than their container and have their content render off-center.
PMTiles:
COG (still has a data problem?):
IIIF (now centered):
Notably, this doesn't fix the IIIF viewer (not the manifest one, just a single IIIF image). It seems to have some kind of height calculation problem. This might be a bug in Clover's single-image viewer, or just a configuration issue?
> Fix viewer sizing for OpenLayers and IIIF viewers

- spec/test_app_templates/lib/generators/test_app_generator.rb
We now only support Rails 7, and no longer build the test app
without javascript, so these Hotwire libraries will always be
installed automatically and don't need special handling.
> Remove special handling for stimulus and turbo gems

- app/helpers/geoblacklight_helper.rb
- lib/generators/geoblacklight/templates/settings.yml
- spec/helpers/geoblacklight_helper_spec.rb
and allow for legacy icons removed in PR #1386 to continue to render
closes #1446
This PR provides two pieces of functionality. 
1. It allows users of old versions of geoblacklight who are using old icons and don't want to update their data to continue to have icons appear.
2. It allows for icons to display when they don't match the icon name without having to create a totally new icon. For example, in the big10 geo portal there is a provider named `UW-Madison Robinson Map Library`. If the user wanted an icon to display for that provider that was the university_of_wisconsin_madison icon they would have to create a new icon component. With this PR they will just have to add a line to the settings file.
```
uw-madison-robinson-map-library: university-of-wisconsin-madison
```
> allow for image mapping

- Rakefile
- compose.yml
Downloading and building Solr and the rebuilding of internal test app so many times was a pain point for our dev team. This PR is meant to make development easier and is not related to production builds. It removes a redundant `engine_cart:generate` statement, adds an option to run Solr in docker, and makes it easier overall to run Solr and the application separately. I followed the pattern we used in Arclight development, another downstream-from-Blacklight rails engine, which has worked pretty well for us.
If approved, I have drafted updated documentation that I will PR in that repo.
> Add docker compose option for solr only and modify Rakefile

- .github/workflows/build-demo-app.yml
- .github/workflows/prune-containers.yml
- lib/generators/geoblacklight/templates/docker/demo-app-Dockerfile
- lib/generators/geoblacklight/templates/docker/demo-app-compose.yml
- lib/generators/geoblacklight/templates/docker/start-server.sh
Build demo/test apps as artifacts and create docker images from them.
- On pull request and main branch push, build demo apps using the template.rb file.
- Generate a docker image from the test app and push into the GitHub package repository.
- Bundle a docker compose file with the downloadable build which runs solr and gbl app.
- Add comment to pull request with link for downloading the build.
- Prune old images monthly.
- Regenerate a new main branch image weekly.
Closes #1448
> Build demo app in CI an push docker images

- lib/generators/geoblacklight/install_generator.rb
We don't use jQuery anymore, so no need to inject code about disabling animations.
> Remove unused jquery-related generator code

- spec/test_app_templates/lib/generators/test_app_generator.rb
This fixes a deprecation warning; `.with_clean_env` was deprecated: https://github.com/castwide/solargraph/issues/252
> Use bundler.with_unbundled_env

- Gemfile
this rails option only works for Rails 6 and before, when turbo was turbolinks. it does nothing now.
> Remove obsolete engine_cart option

- app/assets/stylesheets/geoblacklight/geoblacklight.scss
- lib/generators/geoblacklight/assets_generator.rb
- lib/generators/geoblacklight/templates/assets/_customizations.scss
- lib/generators/geoblacklight/templates/assets/application.scss
- lib/generators/geoblacklight/templates/assets/geoblacklight.scss
- lib/generators/geoblacklight/templates/vite.config.ts
This shifts the structure of the stylesheet to separate building
Geoblacklight's styles from the application itself, so it's a
little more clear where things are coming from.
By taking the imports out of the stylesheet in the gem and moving
them into the generated app, we can get rid of some weird-looking
paths and aliases in Vite.
> Adjust style paths so Vite aliases aren't needed

- lib/generators/geoblacklight/install_generator.rb
- spec/test_app_templates/lib/generators/test_app_generator.rb
This fixes an issue introduced with https://github.com/geoblacklight/geoblacklight/pull/1433 where changes to frontend assets (JS, CSS) don't get picked up in local development and require fully rebuilding the `.internal_test_app`.
The problem is that:
- `yarn add` adds the outer assets directory, which ensures that @geoblacklight/frontend gets added with all its dependencies, but doesn't pick up any change thereafter
- `yarn link` links the outer assets directory, which adds @geoblacklight/frontend _without_ its dependencies, but does pick up changes made later
This PR reverts to the latter strategy and adds a note to make sure that we always include all the dependencies of `@geoblacklight/frontend` in the _generated app's_ package.json, not just geoblacklight's package.json, so that …
> Revert to using `yarn link` so changes are picked up in development

- .github/workflows/ruby.yml
- app/helpers/blacklight_helper.rb
- geoblacklight.gemspec
- spec/spec_helper.rb
Rails 6.1 is EOL in October 2024 and Rails 7.0 is EOL April 2025. In order to allow implementers more flexibility, this PR bumps the max Rails version to 7.2.
> Bump max Rails version to 7.2 in GBL 4

- spec/features/web_services_modal_spec.rb
Fixes #1480 ...I think?
This writes a helper method to open the web services modal the same way every time and ensure it has loaded by asserting that its heading is visible.
It also uses more standard rspec syntax (`:feature` test type, describe/expect/it, etc.) and factors out some repeated elements in the tests.
> Refactor the Web Services modal feature tests

- spec/features/axe_spec.rb
Fixes #1506.
The relationships panel is inserted into the page and then faded in using an animation with a 200ms timing, so it's possible that aXe is seeing it halfway faded-in and calculating color contrast ratios off of that, since the colors are not what we actually see when loading it in the browser.
> Force capybara to wait for relationships to fade in before running aXe

- app/assets/stylesheets/geoblacklight/modules/_blacklight_overrides.scss
- app/components/geoblacklight/header_component.html.erb
According to the screenshots in the thread for PR #1441, the search bar should be centered, but correct me if I am wrong@!
> Center the search bar

- solr/conf/schema.xml
- solr/conf/solrconfig.xml
Several fields changed in Aardvark:
* layer_slug is now id
* layer_geom_type replaced by gbl_resourceClass and gbl_resourceType
We might also want to add resource class/type to the spell checking and suggestions, although I haven't done that here.
This addresses #1502
> update solrconfig.xml and schema.xml

- package.json
This is the next non-private package number available for publishing (via semver) because I `npm publish`ed the preceding few without doing `--access public` 🤦🏻
> Bump frontend package version to 5.0.0-alpha.7

- .gitignore
- lib/generators/geoblacklight/templates/assets/_customizations.scss
- package.json
- vite.config.ts
Closes #1514 
This uses the same strategy as blacklight: bundle things into `app/assets/javascripts` but gitignore it, and then ship everything in `app/assets` (including the bundled `app/assets/javascripts`) _and_ `app/javascript` (unbundled).
This way, the paths inside the package match where things go in your built app, and there's no `copyPublicDir` magic needed to make sure that images or other assets in `app/assets` get included in the npm package: they will always have the same path in the package that they do in the gem.
> Publish unbundled versions of JS assets

- spec/features/bookmarks_spec.rb
- spec/features/layer_inspection_spec.rb
This fixes an HTTP timeout error that could arise when an NYU
fixture was queried over WMS and didn't respond in time, causing
tests to fail.
This commit switches the two tests that used the fixture to use
other, equivalent fixtures to avoid the timeouts.
See also #1492.
> Change tests to stop using NYU fixture

- app/models/concerns/geoblacklight/solr_document/citation.rb
- app/views/catalog/_citation.html.erb
- config/locales/geoblacklight.en.yml
- spec/components/geoblacklight/citation_component_spec.rb
- spec/models/concerns/geoblacklight/solr_document/citation_spec.rb
Removes "Citation info" text from the beginning.
Link shown at the end now varies instead of being a link to the solr document (e.g. earthworks).  Instead, it will look to see if the identifier looks like a URL (could be a DOI or a PURL) and use that if found.  If not found, it will look in the references for a schema.org/url link.  If found, it will use that.  If not, back the current (solr document url)
Fixes #1500
Example:
> change how citations are shown

- Gemfile
- geoblacklight.gemspec
This fixes warnings like:
```
A gemspec development dependency (capybara, >= 2.5.0) is being overridden by a Gemfile dependency (capybara, >= 0).
This behaviour may change in the future. Please remove either of them, or make sure they both have the same requirement
A gemspec development dependency (engine_cart, ~> 2.0) is being overridden by a Gemfile dependency (engine_cart, >= 0).
This behaviour may change in the future. Please remove either of them, or make sure they both have the same requirement
A gemspec development dependency (simplecov, ~> 0.22) is being overridden by a Gemfile dependency (simplecov, >= 0).
This behaviour may change in the future. Please remove either of them, or make sure they both have the same requirement
A gemspec development dependency (standardrb, = 1.0.1) …
```
> Move development dependencies into the gemspec

- Rakefile
- template.rb
See #1265 
This avoids warnings in the generated app about `config/manifest.js` being missing, assets not being precompiled, etc, etc. that arise when sprockets gets used, which is still the default in Rails unless you tell it not to.
It's easier to make sure that rails uses the `-a propshaft` option early on in the build process than to remove and replace sprockets later on in the build process (in a geoblacklight generator) because there's a lot more you have to tear out.
> Force engine_cart and template.rb builds to use propshaft

- .github/workflows/ruby.yml
Update to the latest Solr version and use auto-built images saved in the GitHub package repo instead of Docker Hub.
https://github.com/geoblacklight/geoblacklight-docker/pkgs/container/solr
> Update CI to use new ghrc image and solr 9.6

- lib/generators/geoblacklight/templates/demo-app/compose.yml
- lib/generators/geoblacklight/templates/demo-app/start-server.sh
Reduce confusion when running the demo app docker. The rails server log now matches the port that compose binds to.
> Start docker rails server on port 3001

- app/assets/stylesheets/geoblacklight/modules/_blacklight_overrides.scss
- app/assets/stylesheets/geoblacklight/modules/icon-customization.scss
This rule was not overriding blacklight, so it is misleading to put it in there
> Move rules about iiif-icons out of the blacklight_overrides.scss

- app/assets/stylesheets/geoblacklight/modules/_blacklight_overrides.scss
- lib/generators/geoblacklight/templates/assets/_customizations.scss
- lib/generators/geoblacklight/templates/vite.config.ts
This makes it easier for downstream apps to configure their own logos and results in less overall css.
> Configure the logo rather than overriding

- geoblacklight.gemspec
- spec/spec_helper.rb
As of https://github.com/rails/rails/pull/48847, Ruby 3 Rails apps
don't need the webdrivers gem because the selenium manager handles
managing and installing browser versions on its own.
This removes a deprecation warning that occurs during the build.
> Use selenium-webdriver directly without webdrivers gem

- app/components/geoblacklight/location_leaflet_map_component.rb
The will update [the SETTINGS](https://github.com/geoblacklight/geoblacklight/blob/200d4ab704630d5b53206ffc107c420f6cba4172/app/helpers/geoblacklight_helper.rb#L64) without the duplication.
closes #1591
> don't allow leaflet_options to be updated

- lib/generators/geoblacklight/templates/assets/application.js
Explicitly importing and binding bootstrap to the window object
causes its javascript to be imported twice. We already bundle
bootstrap into geoblacklight's javascript, so we don't need
to explicitly import it beforehand.
Fixes #1566
> Prevent bootstrap from being imported twice

- app/assets/stylesheets/geoblacklight/modules/item.scss
- app/javascript/geoblacklight/initializers/truncation.js
This refactors the truncation logic we have that builds on bootstrap's
collapse functionality. It fixes a problem where the button had the
wrong text after expanding/collapsing.
Also removes a delay that was present because bootstrap sets an
animation length, but we were not actually doing any animation.
Closes #1592
> Refactor truncation for abstracts

- .github/workflows/build-demo-app.yml
Fixes docker builds.
Closes #1597
> Ensure the demo app builder and demo app Dockerfile use the same Ruby version

- app/components/geoblacklight/header_icons_component.html.erb
- app/components/geoblacklight/header_icons_component.rb
- app/models/concerns/geoblacklight/solr_document.rb
- spec/components/geoblacklight/header_icons_component_spec.rb
This slightly refactors the logic in the header icons component that picks a more specific icon to display based on an item's resource type.
For cases where an item had multiple resource types, but one of them was one that mapped to an icon (e.g. "Raster data" and "Nautical charts"), we were sometimes falling back to the resource class ("Datasets"). This change has us use "Raster data" since we know we have a more specific icon for it in that situation.
For more info, see https://github.com/sul-dlss/earthworks/issues/1398.
> Update resource type icon logic

- app/components/geoblacklight/web_services_default_component.html.erb
- app/components/geoblacklight/web_services_wfs_component.html.erb
- app/components/geoblacklight/web_services_wms_component.html.erb
- app/javascript/geoblacklight/controllers/clipboard_controller.js
- app/views/catalog/_citation.html.erb
- spec/features/citations_spec.rb
- spec/features/web_services_modal_spec.rb
This fixes the clipboard copying logic for the web services modal
and adds tests, inspired by #1613.
Closes #1550
> Fix clipboard copy functionality for web services modal

- app/assets/stylesheets/geoblacklight/modules/_base.scss
- app/assets/stylesheets/geoblacklight/modules/leaflet.scss
This fixes an accessibility issue identified by some automated
checkers. See: https://github.com/sul-dlss/earthworks/issues/1432
> Remove transparency of Leaflet's attribution display

- template.rb
This won't work right now because there isn't a v5 released to
rubygems that satisfies the version lock (only prereleases),
but it will as soon as one is released.
Fixes #1610
> Make template builds for v5 actually point at v5

- lib/generators/geoblacklight/templates/base.html.erb
Instead of hardcoding the skip links, this uses the view component
that renders them, which in turn uses Blacklight builtins to
determine where to link to.
Fixes #1580
See also https://github.com/sul-dlss/earthworks/commit/cffc3bee3cbc39d098e3f2fd69a7f2ec59883464
> Switch to using Blacklight's SkipLinksComponent

- app/assets/stylesheets/geoblacklight/modules/geosearch.scss
This code actually adds a white border to the button https://private-user-images.githubusercontent.com/13892693/370072140-4ece882a-7337-42c8-b002-525bfc4aedf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMwMDUxMzIsIm5iZiI6MTc0MzAwNDgzMiwicGF0aCI6Ii8xMzg5MjY5My8zNzAwNzIxNDAtNGVjZTg4MmEtNzMzNy00MmM4LWIwMDItNTI1YmZjNGFlZGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI2VDE2MDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMzhiOWVkMjk5NTdlNmJhYWU4NWNmYzkzMDJlODQ0NTNmMzUzMWU5ZTEyNTAzZGQzYzNjNDgyZjUxNWU2M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.93J71urtvfdN …
> remove unnecessary styles

- app/javascript/geoblacklight/leaflet/controls/layer_opacity.js
- app/javascript/geoblacklight/leaflet/controls/sleep.js
This removes one and changes the other to an error, since it
looked like that's what it was intended to do.
> Remove console.log statements

- .github/workflows/ruby.yml
Maybe this will fix CI failures like https://github.com/geoblacklight/geoblacklight/actions/runs/15028963878/job/42792407413?
> Bump github @actions/checkout to v4

- .github/workflows/ruby.yml
- geoblacklight.gemspec
- spec/test_app_templates/lib/generators/test_app_generator.rb
This backports e8b71065ad0358d2c1b01e521cdb7328a1c99990.
> Drop support for Rails 6 in GBLv4; update GitHub CI

- .github/workflows/ruby.yml
This was fixed in `main` long ago, but is now apparent for `release-4.x` because of #1657 (where you can see tests passed but the CI job failed).
> Prevent conflicting artifact names for GH CI coverage upload
