geoblacklight/geoblacklight

app/assets/stylesheets/geoblacklight/_geoblacklight.scss
app/assets/stylesheets/geoblacklight/modules/search_widgets.scss
spec/features/split_view.html.erb_spec.rb

adds a zindex for search widgets overlaying map

---

lib/generators/geoblacklight/install_generator.rb
lib/generators/geoblacklight/templates/solr_documents
spec/test_app_templates/lib/generators/test_app_generator.rb
spec/test_app_templates/solr_documents

Spec solr_documents generator should be moved to test app generator rather than generic app generator

move solr_documents from install generator to test app generator

---

app/assets/javascripts/geoblacklight/viewers/map.js

Adds in blank alt text for accessiblity (MapQuest Logo)

adds alt text for mapquest logo

---

Rakefile
lib/generators/geoblacklight/install_generator.rb
lib/generators/geoblacklight/templates/config/jetty.yml
lib/tasks/geoblacklight.rake
template.rb

Updates rake tasks to be available to a geoblacklight application. Needed for installation and test app.

updates rake tasks for a geoblacklight adopter

---

app/assets/javascripts/geoblacklight/modules/results.js
lib/geoblacklight.rb
lib/geoblacklight/catalog_helper_override.rb
lib/geoblacklight/view_helper_override.rb
spec/features/split_view.html.erb_spec.rb
spec/lib/geoblacklight/view_helper_override_spec.rb

adds spatial search constraints to breadcrumb

---

app/assets/javascripts/geoblacklight/modules/geosearch.js
lib/geoblacklight/controller_override.rb
spec/features/split_view.html.erb_spec.rb

Constrain search bounds to 360 degrees

---

Gemfile

This fixes an issue with a known security vulnerability in Rails Assets.

fix install for rails-assets issue

---

Gemfile
app/assets/javascripts/geoblacklight/geoblacklight.js
geoblacklight.gemspec
lib/generators/geoblacklight/install_generator.rb
lib/generators/geoblacklight/templates/geoblacklight.js
lib/geoblacklight/engine.rb
template.rb

Hopefully once and for all will resolve issues that new installers with rails-assets.

remove gem dependency of rails-assets

---

app/assets/javascripts/geoblacklight/viewers/map.js

Closes #195 
Punting on configuration by instance and will let that come later when needed. Map now starts here:
cc @mapninja

change default map extent on homepage

---

app/assets/stylesheets/geoblacklight/_geoblacklight.scss
app/assets/stylesheets/geoblacklight/modules/icon-customization.scss
app/assets/stylesheets/geoblacklight/modules/toolbar.scss
app/assets/stylesheets/geoblacklight/modules/web_services.scss
app/helpers/geoblacklight_helper.rb
app/views/catalog/_web_services.html.erb
app/views/catalog/web_services.html
app/views/catalog/web_services.js.erb
config/locales/geoblacklight.en.yml
lib/generators/geoblacklight/templates/catalog_controller.rb
lib/generators/geoblacklight/templates/settings.yml
lib/geoblacklight.rb
lib/geoblacklight/controller_override.rb
lib/geoblacklight/routes.rb
spec/controllers/catalog_controller_spec.rb
spec/features/web_services_modal_spec.rb

Closes #66 
Leaving out auto copy link for later

adds in webservices document tools

---

app/assets/javascripts/geoblacklight/modules/collapse.js
app/assets/stylesheets/geoblacklight/modules/results.scss
app/views/catalog/_index_split_default.html.erb

adds in caret in results view for toggle

---

app/views/catalog/_search_form_no_navbar.html.erb

Makes search label and placeholder configurable/different

use new BL5.9.3 i18n keys

---

README.md
Rakefile
lib/tasks/configure_solr.rake
lib/tasks/geoblacklight.rake

Closes #281 
Needed for Windows users that do not ship with `curl`

removes curl calls in favor of ruby

---

app/assets/stylesheets/geoblacklight/modules/results.scss
app/views/catalog/_home_text.html.erb
app/views/catalog/_index_split_default.html.erb

Inline with work being done upstream in Blacklight
https://github.com/projectblacklight/blacklight/pull/1124

modify results headings to meet wcag guidelines

---

app/assets/javascripts/geoblacklight/basemaps.js
app/assets/javascripts/geoblacklight/viewers/map.js
lib/generators/geoblacklight/templates/geoblacklight.js

refinements to config-basemap branch

---

lib/geoblacklight/reference.rb
lib/geoblacklight/references.rb
spec/lib/geoblacklight/reference_spec.rb
spec/lib/geoblacklight/references_spec.rb

24a82fa adds comments and specs for Geoblacklight::Reference
b448d91 adds comments, also makes some methods private

Adds documentation and tests for Reference and References

---

vendor/assets/javascripts/leaflet-iiif.js

Updates Leaflet IIIF module to 0.0.7. Moves tile requests to w,h format.

update leaflet-iiif to 0.0.7

---

app/helpers/blacklight_helper.rb
app/helpers/geoblacklight_helper.rb
app/views/catalog/_show_default_viewer_container.html.erb
app/views/catalog/_web_services.html.erb
app/views/catalog/_web_services_default.html.erb
app/views/catalog/_web_services_wfs.html.erb
app/views/catalog/_web_services_wms.html.erb
lib/generators/geoblacklight/templates/catalog_controller.rb
lib/geoblacklight.rb
lib/geoblacklight/document_presenter.rb
lib/geoblacklight/download.rb
lib/geoblacklight/geoblacklight_helper_behavior.rb
lib/geoblacklight/wms_layer.rb
spec/features/web_services_modal_spec.rb
spec/helpers/geoblacklight_helpers_spec.rb
spec/lib/geoblacklight/document_presenter_spec.rb
spec/lib/geoblacklight/geoblacklight_helper_behavior_spec.rb

This commit also adds the pattern to start removing hard coded Solr field values from the view using Document Presenter pattern
Closes #348

Add webservices layer id enhancement

---

Rakefile
spec/teaspoon_env.rb

Fix failing teaspoon tests

---

lib/generators/geoblacklight/install_generator.rb

Needed to cut 0.11.1 without breaking compatibility.

release backport for 0.11

---

lib/generators/geoblacklight/install_generator.rb

Re-opening this issue. @mejackreed

fix issue with precompiling favicon

---

geoblacklight.gemspec
spec/models/concerns/geoblacklight/solr_document/finder_spec.rb

This PR loosens up Blacklight requirements in preparation for Blacklight 6.0

update to work with Blacklight >~ 5.9 < 6

---

spec/features/esri_viewer_spec.rb

The tests were currently failing due to the position of the pending
statement.

Move pending statement to top

---

app/assets/stylesheets/geoblacklight/modules/toolbar.scss
app/views/catalog/_downloads.html.erb

Remove wrapping div to fix split button second line

---

app/assets/javascripts/geoblacklight/basemaps.js
app/assets/javascripts/geoblacklight/viewers/map.js
app/helpers/geoblacklight_helper.rb
lib/generators/geoblacklight/templates/catalog_controller.rb
spec/features/configurable_basemap_spec.rb
spec/helpers/geoblacklight_helpers_spec.rb

resolves the issue where the MapQuest OSM basemap is going away.

make Cartodb the default postiron basemap

---

README.md

Adds waffle.io badge to the README.

Add waffle.io badge to README

---

app/assets/javascripts/geoblacklight/basemaps.js
app/assets/javascripts/geoblacklight/viewers/map.js

This PR makes basemaps higher resolution when displayed on a retina monitor. Not sure how I feel about it. They look very sharp (obvs), but are harder to read and take a noticeably longer amount of time to load.

CartoDB basemaps display higher resolution on retina screen

---

spec/features/esri_viewer_spec.rb
spec/features/home_page_spec.rb
spec/fixtures/solr_documents/actual-papermap1.json
spec/fixtures/solr_documents/actual-raster1.json
spec/fixtures/solr_documents/esri-dynamic-layer-single-layer.json
spec/fixtures/solr_documents/esri-feature-layer.json
spec/fixtures/solr_documents/esri-wms-layer.json
spec/fixtures/solr_documents/restricted-line.json

Closes #434.
- Fixes formatting on a few fixture documents.
- Updates a few esri fixtures with actual documents from OpenGeoMetadata.

Fix fixtures

---

app/assets/javascripts/geoblacklight/modules/util.js
app/assets/javascripts/geoblacklight/viewers/esri.js
app/assets/javascripts/geoblacklight/viewers/wms.js
spec/features/linkified_attribute_table_spec.rb
spec/javascripts/util_spec.js

add linkify utility and linkify attribute table values

---

spec/features/esri_viewer_spec.rb
spec/features/layer_opacity_spec.rb
spec/fixtures/solr_documents/esri-dynamic-layer-all-layers.json
spec/fixtures/solr_documents/esri-feature-layer.json
spec/fixtures/solr_documents/esri-image-map-layer.json
spec/fixtures/solr_documents/esri-tiled_map_layer.json

Update fake esri fixtures with real provenance so that icons show up properly.

update fake esri fixtures with real provenance

---

app/assets/stylesheets/geoblacklight/_geoblacklight.scss
app/assets/stylesheets/geoblacklight/modules/facets.scss
app/helpers/geoblacklight_helper.rb
app/views/catalog/_icon_facet.html.erb

Not really sure how to test this.. but fixes #438 
@sgbalogh what do you think? The "Restricted" / "Public" icons still seem off?

fixes our facet icon alignment issue

---

app/assets/javascripts/geoblacklight/modules/util.js

Fixes an issue where other libraries were having interaction issues. Issues included:
- some implementations of Google Analytics
- Blacklight Range Limit

remove unintended global use strict; since we cant control everything

---

schema/geoblacklight-schema.json
schema/geoblacklight-schema.md

This PR is connected to #412. Just clarified the description/intent for `dct_isPartOf_sm`

update documentation for isPartOf

---

app/assets/stylesheets/geoblacklight/modules/icon-customization.scss
app/assets/stylesheets/geoblacklight/modules/toolbar.scss
app/models/concerns/geoblacklight/solr_document.rb
app/views/catalog/_data_dictionary.html.erb
config/locales/geoblacklight.en.yml
lib/generators/geoblacklight/templates/catalog_controller.rb
lib/geoblacklight/constants.rb
spec/features/data_dictionary_download_spec.rb
spec/fixtures/solr_documents/baruch_documentation_download.json
spec/models/concerns/geoblacklight/solr_document_spec.rb

https://github.com/geoblacklight/geoblacklight/issues/424

Adds URI constant for data_dictionary (/documentation download)

---

schema/geoblacklight-schema.json

This PR updates the `id` in the JSON Schema definition to include `v1.0`, and updates the `description`.

Fix Schema URI

---

schema/geoblacklight-schema.json

Deleted fields that are not technically required.

Fix required fields in schema validation

---

Rakefile

Adds the back the gem release rake task.

Add the gem release task back to the Rakefile

---

lib/tasks/geoblacklight.rake

Lazy-load solr_wrapper gem only in the task that requires it

---

app/helpers/geoblacklight_helper.rb
spec/helpers/geoblacklight_helpers_spec.rb

This will enable more adopters, potentially with alpha numeric chars in their names. eg "Lewis & Clark"

Remove non alpha numeric

---

app/assets/javascripts/geoblacklight/modules/results.js
app/models/concerns/geoblacklight/solr_document.rb
spec/features/home_page_spec.rb
spec/features/missing_metadata_spec.rb
spec/fixtures/solr_documents/no_spatial.json

Fixes the issue where solr_geom and layer_id_s is not available

---

lib/geoblacklight/wms_layer/feature_info_response.rb
spec/lib/geoblacklight/wms_layer/feature_info_response_spec.rb

Bugfix for getFeatureInfo responses with multiple rows

---

app/views/relation/_ancestors.html.erb
app/views/relation/_descendants.html.erb

Wrap descendant and ancestor labels in li tags

---

geoblacklight.gemspec
spec/factories/user.rb
spec/spec_helper.rb
spec/support/features/session_helpers.rb

Resolves a deprecation warning, and moves away from unsupported FactoryGirl.

migrate to FactoryBot

---

app/views/catalog/_icon_facet.html.erb
spec/features/split_view.html.erb_spec.rb

add "more" link to icon facet partial

---

schema/format-values.md
schema/geoblacklight-schema-deprecated.md
schema/geoblacklight-schema.md
schema/geometry-type-values.md
schema/type-values.md

I am submitting this as a pr to share what I have developed so far.

New metadata documentation

---

lib/generators/geoblacklight/templates/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

Modifies the CatalogController template for setting .default_per_page to set the default Solr `:rows`

---

app/assets/javascripts/geoblacklight/modules/util.js
app/assets/javascripts/geoblacklight/viewers/index_map.js
spec/features/index_map_spec.rb
spec/features/metadata_panel_spec.rb
spec/fixtures/solr_documents/point_index_map.json

Closes #610 
Thanks to @kgjenkins for providing the index map.
++ to geo4libcamp group who paired to create the fixture metadata

adds support for point based index maps

---

CONTRIBUTING.md

This PR intends to update our contributing guide to reflect current community practice with an eye towards more inclusiveness.
Any and all feedback is most welcome!
cc @eliotjordan @jrgriffiniii

update contributing guide to reflect current community practices

---

app/assets/javascripts/geoblacklight/modules/geosearch.js
app/views/catalog/_home_text.html.erb
app/views/catalog/_search_form_no_navbar.html.erb
app/views/catalog/metadata/_markup.html.erb
geoblacklight.gemspec

Switching from Glyphicons to FontAwesome

---

app/assets/javascripts/geoblacklight/basemaps.js
lib/generators/geoblacklight/templates/catalog_controller.rb
spec/features/configurable_basemap_spec.rb

Added a few new carto baselayers and fixed the old references to CartoDB.
Closes #535

adds carto basemap layers

---

app/views/catalog/_facets.html.erb

Fixes #656  Reflow #facets children for Bootstrap 4's .navbar expectactions.

Resolve mobile limits/facet toggle alignment

---

spec/fixtures/solr_documents/public_polygon_mit.json

Fixes failing the functional test suites found in https://travis-ci.org/geoblacklight/geoblacklight/builds/409986802?utm_source=github_status&utm_medium=notification

Updating the MIT fixture WMS endpoints

---

lib/generators/geoblacklight/install_generator.rb

Disable jQuery animations during tests

---

app/assets/stylesheets/geoblacklight/modules/item.scss
app/views/catalog/_show_default.html.erb
app/views/catalog/_show_default_attribute_table.html.erb
app/views/catalog/_show_default_viewer_container.html.erb

Placing the layer preview and attributes into separate rows on the record show interface

---

README.md

Swap Travis build badge for CircleCI badge

---

.coveralls.yml
.rubocop.yml
app/controllers/download_controller.rb
lib/geoblacklight/download.rb
lib/geoblacklight/metadata_transformer/base.rb
lib/geoblacklight/metadata_transformer/fgdc.rb
lib/geoblacklight/metadata_transformer/iso19139.rb
spec/controllers/download_controller_spec.rb
spec/helpers/carto_helper_spec.rb
spec/helpers/geoblacklight_helper_spec.rb
spec/lib/geoblacklight/document_presenter_spec.rb
spec/lib/geoblacklight/download/hgl_download_spec.rb
spec/lib/geoblacklight/download_spec.rb
spec/lib/geoblacklight/geoblacklight_helper_behavior_spec.rb
spec/lib/geoblacklight/metadata/base_spec.rb
spec/lib/geoblacklight/references_spec.rb
spec/lib/geoblacklight/wms_layer_spec.rb
spec/models/concerns/geoblacklight/solr_document/carto_spec.rb
spec/models/concerns/geoblacklight/solr_document/finder_spec.rb
spec/models/concerns/geoblacklight/spatial_search_behavior_spec.rb
spec/spec_helper.rb

Increasing the test coverage to 100%

---

app/assets/stylesheets/geoblacklight/modules/icon-customization.scss
app/assets/stylesheets/geoblacklight/modules/results.scss
app/views/catalog/_home_text.html.erb

Resolve homepage and search results mobile view issues.
* Homepage: single column mobile view
* Search results: result list item spacing
Fixes: #694, #695

694 mobile view responsiveness

---

schema/format-values.md

Adds the "GeoPackage" value to the list of `dc_format_s` values.  Progresses towards a resolution for #608

Adding GeoPackage to the list of format values

---

app/assets/javascripts/geoblacklight/modules/geosearch.js

Ensures that resizing the Leaflet Map does not trigger any dynamic searches

---

spec/controllers/catalog_controller_spec.rb
spec/controllers/download_controller_spec.rb
spec/features/download_layer_spec.rb
spec/features/layer_inspection_spec.rb
spec/features/layer_opacity_spec.rb
spec/features/layer_preview_spec.rb
spec/features/metadata_panel_spec.rb
spec/features/split_view.html.erb_spec.rb
spec/fixtures/solr_documents/esri-feature-layer.json
spec/fixtures/solr_documents/public_polygon_mit.json
spec/fixtures/solr_documents/umn_metro_result1.json

Fix issues with broken references in fixtures

---

app/assets/javascripts/geoblacklight/viewers/wms.js

I can also submit this to `master` as well if needed. Fixes #712

use a backwards compatible ujs adapter

---

app/helpers/carto_helper.rb
app/helpers/geoblacklight_helper.rb
lib/generators/geoblacklight/templates/settings.yml
spec/factories/user.rb
spec/helpers/carto_helper_spec.rb
spec/helpers/geoblacklight_helper_spec.rb

Remove deprecations

---

app/views/catalog/_facet_tag_layout.html.erb

Update facet_tag_layout to include more_html from BL

---

geoblacklight.gemspec

Updating geo_combine to releases 0.4.x

---

app/assets/javascripts/geoblacklight/basemaps.js

Ok... sorry for the foibles all =)

adds s for security

---

Rakefile
app/assets/javascripts/geoblacklight/basemaps.js
geoblacklight.gemspec
schema/geoblacklight-schema.md
schema/schema-commentary.md
spec/fixtures/solr_documents/point_index_map.json

Added text for each field in commentary, and shortened a few entry guidelines in the schema.

Schema enhancements km

---

schema/geoblacklight-schema.md
schema/schema-commentary.md

I made some more changes etc. Small stuff but continuing to work on this.

makes some more small changes and suggestions

---

schema/geoblacklight-schema.md
schema/schema-commentary.md

a couple more small changes

---

spec/fixtures/solr_documents/index-map-polygon-no-downloadurl.json
spec/fixtures/solr_documents/index-map-polygon.json

Keeps all the index maps together for test app under single value for `dc_subject_sm` facet.
> @kgjenkins As we discussed 😄

Consistent casing for index map fixtures (subject)

---

spec/features/index_map_spec.rb
spec/spec_helper.rb

Fix test causing CI failures

---

app/assets/stylesheets/geoblacklight/_blacklight_overrides.scss
app/assets/stylesheets/geoblacklight/modules/metadata.scss
app/views/catalog/_metadata.html.erb

766 metadata preview modal

---

.circleci/config.yml
spec/test_app_templates/lib/generators/test_app_generator.rb
template.rb

Add fix rails/sqlite3 issue

---

.solr_wrapper
solr/conf/schema.xml

First reported by @dsiegal . Upstream PR in Blacklight https://github.com/projectblacklight/blacklight/pull/2087

Solr 8 compatibility fix

---

geoblacklight.gemspec
lib/generators/geoblacklight/templates/package.json
spec/test_app_templates/lib/generators/test_app_generator.rb
template.rb

Relax webpacker version requirements

---

geoblacklight.gemspec

remove selenium-webdriver

---

app/helpers/geoblacklight_helper.rb
app/views/catalog/_exports.html.erb
lib/generators/geoblacklight/templates/settings.yml
spec/features/exports_spec.rb

Configure the display of the Carto and ArcGIS links

---

spec/fixtures/solr_documents/iiif-eastern-hemisphere.json

addresses the request @ewlarson made in #843

swaps url in iiif fixture

---

app/assets/stylesheets/geoblacklight/modules/item.scss
config/locales/geoblacklight.en.yml
lib/generators/geoblacklight/templates/settings.yml

Not sure if this is controversial, but added a pointer cursor to help text

Fixes #844 also adds a cursor/pointer

---

.circleci/config.yml

Builds off of #876 and resolves #868

Adds a scheduled, nightly job for running the CircleCI builds

---

.circleci/config.yml

Resolves #789. I have adjusted the names of the cache keys before rebasing (they weren't as clear before), and I will restart the build in order to link to the difference in time (demonstrating the slight in gain in performance).

Parallelizing the RSpec test suites and improving the caching for the Gem bundle and internal test app.

---

app/models/concerns/geoblacklight/solr_document.rb
spec/models/concerns/geoblacklight/solr_document_spec.rb

Closes sul-dlss/earthworks#637

Better support for documents w/o rights data

---

app/assets/javascripts/geoblacklight/modules/geosearch.js
app/assets/javascripts/geoblacklight/modules/home.js

Part of https://github.com/sul-dlss/earthworks/issues/669

Drop a placeholder href onto the map search button so it is focusable

---

app/views/catalog/_document_split.html.erb
app/views/catalog/_home_text.html.erb
app/views/catalog/_show_default_viewer_container.html.erb
config/locales/geoblacklight.en.yml
vendor/assets/stylesheets/leaflet.css

Fixes https://github.com/sul-dlss/earthworks/issues/669

Map accessibility

---

.circleci/config.yml
geoblacklight.gemspec
lib/generators/geoblacklight/install_generator.rb
spec/views/catalog/_show_tools.html.erb_spec.rb

Re-starting some of the work in #891

Add support for rails 6

---

.rubocop.yml
spec/features/relations_spec.rb

Parse relations JSON response to make specs compatible with Solr 8.6

---

app/assets/stylesheets/geoblacklight/modules/results.scss
app/views/catalog/_index_split_default.html.erb
config/locales/geoblacklight.en.yml
spec/features/split_view.html.erb_spec.rb

Part of https://github.com/sul-dlss/earthworks/issues/706

Change the layout of the index results display

---

app/assets/javascripts/geoblacklight/downloaders/downloader.js
app/assets/javascripts/geoblacklight/viewers/esri.js
app/assets/javascripts/geoblacklight/viewers/wms.js
app/assets/stylesheets/geoblacklight/geoblacklight.scss
app/assets/stylesheets/geoblacklight/modules/downloads.scss
app/assets/stylesheets/geoblacklight/modules/results.scss
geoblacklight.gemspec
lib/geoblacklight/engine.rb

Remove geoblacklight-icons and font-awesome dependencies fixes #960

---

spec/features/multiple_downloads_spec.rb

Rubocop fix in multiple_downloads_spec

---

bin/coverage.rb
geoblacklight.gemspec
lib/generators/geoblacklight/templates/catalog_controller.rb
spec/views/catalog/_show_tools.html.erb_spec.rb

Fix test suit

---

.circleci/config.yml

Bug fix: run nightly test build against main not master

---

.gitignore
spec/features/download_layer_spec.rb
spec/fixtures/solr_documents/public_iiif_princeton.json
spec/lib/geoblacklight/references_spec.rb

closes #977
@eliotjordan can you confirm the urls I added are the correct ones?

Update princeton iif urls

---

spec/test_app_templates/Gemfile.extra

Until github/view_component#642 is resolved

Temporarily prevent us from using view_component v2.26.0

---

lib/generators/geoblacklight/templates/settings.gbl_v1.yml

Adds settings.gbl_v1.yml for use with GeoBlacklight Metadata Schema 1.0.

4.x settings gbl 1.0

---

.github/workflows/ruby.yml

Update CI ruby versions and fix CI bundler issue

---

solr/conf/solrconfig.xml

Update solrconfig to support latest solr version

---

.gitignore
.solr_wrapper

- Added .tool-versions file to .gitignore for users who use asdf. Closes #1123 
- Set solr instance directory to tmp/solr so that users without admin access of computers can run solr. Closes #1124

Developer enhancements

---

config/locales/geoblacklight.en.yml
lib/generators/geoblacklight/templates/settings.yml
spec/features/web_services_modal_spec.rb
spec/fixtures/solr_documents/tms.json

- Added WMTS link to web services modal for mosaics. Closes #1127

Added WMTS link to web services modal for mosaics

---

.rubocop.yml
app/helpers/geoblacklight_helper.rb
geoblacklight.gemspec
spec/helpers/geoblacklight_helper_spec.rb
spec/lib/geoblacklight/download_spec.rb
spec/lib/geoblacklight/metadata/base_spec.rb
spec/models/concerns/geoblacklight/solr_document/inspection_spec.rb
template.rb

Silence new cops warning

---

solr/conf/schema.xml
spec/fixtures/solr_documents/princeton-parent.json

Closes #1108 
Supersedes #1109

Remove publisher_sort

---

lib/generators/geoblacklight/templates/catalog_controller.rb
lib/generators/geoblacklight/templates/settings.yml

Update settings key from ISO_TOPIC_CATEGORY to THEME

---

.github/ISSUE_TEMPLATE.md

changed reference from master to main

---

app/views/catalog/_index_split_default.html.erb
spec/features/split_view.html.erb_spec.rb

Add microdata to search results' title and description

---

geoblacklight.gemspec

Require blacklight 7.12

---

spec/test_app_templates/lib/generators/test_app_generator.rb

Install webpacker in test app

---

.github/workflows/ruby.yml

Re-add pull_request trigger

---

app/assets/stylesheets/geoblacklight/modules/item.scss

Ensure oembed iframe is the same height as its container

---

schema/geoblacklight-schema-aardvark.json

Remove enumerated theme values

---

spec/spec_helper.rb

Update Capybara config to fix Selenium deprecation

---

app/helpers/geoblacklight_helper.rb
spec/helpers/geoblacklight_helper_spec.rb

Use a different export format I18n key for export links.

---

app/assets/stylesheets/geoblacklight/modules/sidebar.scss

Add bottom margin to relation cards
Fixes #1212

CSS Fix - Relation cards bottom margin

---

app/models/concerns/geoblacklight/bbox_filter_field.rb
app/views/shared/_header_navbar.html.erb
lib/geoblacklight/bounding_box.rb
spec/controllers/wms_controller_spec.rb
spec/lib/geoblacklight/metadata_transformer/fgdc_spec.rb
spec/lib/geoblacklight/metadata_transformer/iso19139_spec.rb
spec/lib/geoblacklight/references_spec.rb
spec/lib/geoblacklight/wms_layer_spec.rb
spec/models/concerns/geoblacklight/bbox_filter_field_spec.rb
spec/models/concerns/geoblacklight/bbox_filter_query_spec.rb
spec/spec_helper.rb

add Blacklight 7.25+ compatible changes to `Geoblacklight::BboxFilterField`
avoid deprecated behaviors

Blacklight 7.25 compatible filter changes

---

CODE_OF_CONDUCT.md
README.md
schema/geoblacklight-schema-1.0.json

This fixes #1226 --I've updated links and references to the former wiki.

update links to former gbl wiki

---

README.md

Now that our Zenodo record is published, we can link to it in the README!

Add zenodo DOI badge to README

---

lib/generators/geoblacklight/install_generator.rb

Remove redundant heredoc delimiter quotes

---

.gitignore
app/views/catalog/_citation.html.erb
spec/features/citations_spec.rb

Pull Request for https://github.com/geoblacklight/geoblacklight/issues/926

Add Citation to Clipboard

---

app/assets/javascripts/geoblacklight/basemaps.js

update OSM tile URL

---

lib/generators/geoblacklight/templates/settings.gbl_v1.yml
lib/generators/geoblacklight/templates/settings.yml

use integers in index map style

---

app/controllers/download_controller.rb
config/locales/geoblacklight.en.yml
spec/features/download_layer_spec.rb

PR for https://github.com/geoblacklight/geoblacklight/issues/1240

update error message and test

---

lib/generators/geoblacklight/templates/settings.yml
spec/features/web_services_modal_spec.rb

Add COG and PMTiles to web services modal

---

lib/generators/geoblacklight/templates/base.html.erb

put geoblacklight version in a meta tag

---

spec/features/home_page_spec.rb

Adds a test for version meta tag introduced in https://github.com/geoblacklight/geoblacklight/pull/1337

Add test for version tag

---

app/components/geoblacklight/location_leaflet_map_component.html.erb
app/components/geoblacklight/location_leaflet_map_component.rb
app/views/catalog/_document_split.html.erb

Merging into [ @1271-vc-home](https://github.com/geoblacklight/geoblacklight/tree/1271-vc-home) because it relies on the work there.

move document_split map to component, make map sticky

---

app/components/geoblacklight/location_leaflet_map_component.html.erb
app/components/geoblacklight/location_leaflet_map_component.rb
app/helpers/blacklight_helper.rb
app/views/catalog/_document_split.html.erb
app/views/catalog/_home_text.html.erb

closes #1271  and closes #1273

move home and search result maps to location_leaflet_map_component

---

app/components/geoblacklight/data_dictionary_download_component.html.erb
app/components/geoblacklight/data_dictionary_download_component.rb
app/views/catalog/_data_dictionary.html.erb
lib/generators/geoblacklight/templates/catalog_controller.rb

Move the data dictionary show tool to its own component

---

app/components/geoblacklight/web_services_component.html.erb
app/components/geoblacklight/web_services_component.rb
app/components/geoblacklight/web_services_default_component.html.erb
app/components/geoblacklight/web_services_default_component.rb
app/components/geoblacklight/web_services_wfs_component.html.erb
app/components/geoblacklight/web_services_wfs_component.rb
app/components/geoblacklight/web_services_wms_component.html.erb
app/components/geoblacklight/web_services_wms_component.rb
app/helpers/blacklight_helper.rb
app/helpers/geoblacklight_helper.rb
app/views/catalog/_web_services.html.erb
app/views/catalog/web_services.html.erb
spec/components/geoblacklight/web_services_component_spec.rb
spec/helpers/geoblacklight_helper_spec.rb

move web-services to components

---

Gemfile

This reformats the Gemfile and updates the engine_cart stanza,
since we were using a very old one.

Update the Gemfile

---

spec/lib/geoblacklight/wms_layer_spec.rb

This increases coverage to 100%, which makes CI happy

Add a test for WMS layer feature info

---

app/javascript/geoblacklight/metadata_download.js
app/javascript/geoblacklight/truncation.js

For moderinize-js branch.
- Fixes read more link on item page
- Fix metadata download button so it works

Pr cleanup

---

app/javascript/controllers/leaflet_viewer_controller.js

This is what the default map should look like if no protocol

fix default map to have bounds overlay

---

spec/components/geoblacklight/header_icons_component_spec.rb

Remove 'puts' in a test

---

app/views/catalog/_show_sidebar_static_map.html.erb

Make static maps use the leaflet stimulus controller

---

.github/workflows/ruby.yml

Rails 6.1 is not receiving security updates.

Update CI versions of Ruby and Rails

---

template.rb

Updates template.rb to allow installing development branches into a new rails app.
1. Uses branch ruby code.
2. Uses latest geoblacklight frontend package.
```
BRANCH=my_branch rails new app_name -m /path/to/template.rb
```

Add ability to run template.rb with a branch

---

app/assets/stylesheets/geoblacklight/modules/index_maps.scss
app/javascript/controllers/leaflet_viewer_controller.js
app/javascript/leaflet/controls/layer_opacity.js
app/javascript/leaflet/inspection.js
app/javascript/leaflet/layer_index_map.js
app/javascript/leaflet/layers.js
app/javascript/leaflet/utils.js
lib/generators/geoblacklight/templates/settings.yml
lib/geoblacklight/wms_layer/feature_info_response.rb
spec/lib/geoblacklight/wms_layer/feature_info_response_spec.rb

- Add opacity controller to index maps #1343
- Update the layer color to the selected color set in settings.
- fixed opacity for arcgis feature layer
- changed getFeatureInfo to json instead of html, #612
- Have selected portion be highlighted, #1432
closes #612
closes #1343
closes #1432

Image layer highlighting

---

.github/workflows/build-demo-app.yml
.github/workflows/prune-containers.yml

Closes #1453 
- Rebuild base image manually or on a schedule
- Fix delete image job and set to two week schedule

Rebuild base image manually or on a schedule

---

app/javascript/leaflet/controls/layer_opacity.js

make layer opacity keyboard accessible, closes #1461

---

app/components/geoblacklight/login_link_component.rb
spec/components/geoblacklight/login_link_component_spec.rb

don't display login link component if logged in

---

app/views/catalog/_document_split.html.erb

don't hardcode results component

---

spec/features/esri_viewer_spec.rb
spec/fixtures/solr_documents/README.md
spec/fixtures/solr_documents/esri-tiled_map_layer.json

Replacement fixture as noted in #1408 
See https://geodev.btaa.org/catalog/31567cf1-bad8-4bc5-8d57-44b96c207ecc for live version

Replaces Esri Tiled fixture

---

app/assets/stylesheets/geoblacklight/modules/icon-customization.scss
app/components/geoblacklight/document_component.html.erb
app/views/catalog/_show_header_default.html.erb

fix header to include icons

---

app/components/geoblacklight/login_link_component.html.erb

(possibly) fixes #1464 
**Before (wider)** 
**After (wider)** 
**After (narrower)**

add class to make login button full width like other sidebar buttons

---

.github/workflows/ruby.yml
spec/spec_helper.rb

Add Rails 7.2 to CI test matrix.

Test Rails 7.2 in CI matrix in GBL 5

---

app/components/geoblacklight/static_map_component.rb
app/javascript/controllers/leaflet_viewer_controller.js
spec/fixtures/solr_documents/README.md
spec/fixtures/solr_documents/complex-geom.json

* Add new BTAA complex-geom.json fixture
* Add leaflet-viewer-draw-initial-bounds-value to static_map_component.rb
* Adjusts logic in the leaflet_viewer_controller.js to support complex geoms
* Styles the bounding box polygon as a dashed border for complex geoms
Fixes #1482 
Fixes #1350

Sidebar Map - Display item geom/bbox

---

app/components/geoblacklight/item_map_viewer_component.rb
app/components/geoblacklight/location_leaflet_map_component.rb
app/components/geoblacklight/static_map_component.rb
app/javascript/controllers/leaflet_viewer_controller.js
app/javascript/leaflet/constants.js
lib/generators/geoblacklight/templates/settings.yml

Customizable hover

---

CONTRIBUTING.md

A few more updates following up on #1462 and #1460

Tweaks to contributing guide

---

geoblacklight.gemspec
lib/geoblacklight.rb
lib/geoblacklight/metadata/base.rb
lib/geoblacklight/routes.rb

Zeitwerk is the autoloader for rails.  We can use it and then we don't have to have so many "require" statements.

Use zeitwerk

---

app/components/geoblacklight/viewer_help_text_component.rb

fix help text popover

---

spec/fixtures/solr_documents/multiple-downloads.json

We must have inadvertently removed the GeoServer ID from this record.

Add wxs id

---

app/components/geoblacklight/relations_component.html.erb
app/components/geoblacklight/relations_component.rb
app/components/geoblacklight/viewer_help_text_component.rb
app/helpers/geoblacklight_helper.rb
app/models/concerns/geoblacklight/solr_document.rb
app/views/relation/index.json.jbuilder
lib/geoblacklight/download.rb

The former preserves encapsulation

Prefer public_send over send

---

app/components/geoblacklight/viewer_help_text_component.rb

set data-bs-title for help text

---

app/javascript/geoblacklight/controllers/leaflet_viewer_controller.js

don't add second overlay for geosearch

---

app/javascript/geoblacklight/controllers/leaflet_viewer_controller.js

allow for BOUNDSOVERLAY to not be set

---

app/assets/stylesheets/geoblacklight/modules/_blacklight_overrides.scss
app/assets/stylesheets/geoblacklight/modules/home.scss
app/assets/stylesheets/geoblacklight/modules/icon-customization.scss

This allows people to customize without needing sass

Convert to using css variables

---

app/assets/stylesheets/geoblacklight/modules/_base.scss
app/assets/stylesheets/geoblacklight/modules/layer_opacity.scss
app/assets/stylesheets/geoblacklight/modules/mixins.scss

Inline a mixin that is only used once

---

app/assets/stylesheets/geoblacklight/modules/item.scss

The viewer-container is no longer within the document element

Prune unused styles

---

lib/geoblacklight/metadata/base.rb

Require geo_combine

---

app/assets/stylesheets/geoblacklight/modules/item.scss

Reverts geoblacklight/geoblacklight#1562
Some viewers do not display without min height.

Revert "Prune unused styles"

---

app/javascript/geoblacklight/controllers/leaflet_viewer_controller.js

overlays have same custom styling

---

app/controllers/download_controller.rb

This back ports [the fix that @peetucket made](https://github.com/geoblacklight/geoblacklight/pull/1398/files) to the 4.x release branch.

use flash.now instead of flash when rendering

---

.github/workflows/ruby.yml

Use docker compose Solr in CI

---

.github/workflows/ruby.yml

Disable importmap tests until a solution is found

---

app/views/catalog/_document_split.html.erb

fix bookmarks page links

---

lib/geoblacklight/version.rb

This matches the latest version of the frontend assets package.

Set the gem version to 5.0.0-alpha.10

---

app/assets/stylesheets/geoblacklight/modules/item.scss
app/javascript/geoblacklight/leaflet/inspection.js

fixes #1577 for geoblacklight 5

add crosshair cursor on inspectable items

---

lib/generators/geoblacklight/templates/demo-app/compose.yml

Pin demo app solr version

---

.github/workflows/build-demo-app.yml
.github/workflows/ruby.yml
.solr_wrapper
Rakefile
geoblacklight.gemspec
lib/generators/geoblacklight/install_generator.rb
lib/tasks/geoblacklight.rake
spec/test_app_templates/lib/generators/test_app_generator.rb
template.rb

Remove solr_wrapper dependency and use docker

---

Rakefile
lib/tasks/geoblacklight.rake

- **Improve rake tasks to fix CI failure**
- **Remove unneeded rake tasks**
Closes #1618

Improvements to fix CI and remove unneeded rake tasks

---

lib/geoblacklight/version.rb
package.json

This will let us pick up the style changes and other fixes that have been made in the past month or so. Will need to build & publish the frontend package afterward.

Update version to 5.0.0-alpha.11

---

app/assets/stylesheets/geoblacklight/modules/results.scss
app/components/geoblacklight/static_map_component.rb
app/javascript/geoblacklight/controllers/leaflet_viewer_controller.js
app/javascript/geoblacklight/leaflet/controls/sleep.js
lib/generators/geoblacklight/templates/settings.yml

closes #1554
Default behavior
https://github.com/user-attachments/assets/559f0079-b8ec-42e0-8365-3a5a25cc4a65
Settings updated to include hover/new message

add click to wake to map

---

Rakefile

Ensure the right JS pipeline is selected for Rake tasks

---

geoblacklight.gemspec

This is the lowest version we test at.

Set a minimum required ruby version

---

lib/generators/geoblacklight/assets/importmap_generator.rb

This has been resolved upstream.

Remove workaround for blacklight asset pipeline issue

---

app/javascript/geoblacklight/controllers/openlayers_viewer_controller.js
app/javascript/geoblacklight/openlayers/inspection.js
app/models/concerns/geoblacklight/solr_document/inspection.rb
spec/features/layer_inspection_spec.rb

Closes #1490
Adds layer inspection for PMTiles layers.

Add inspection to PMTiles layers
